"""Deterministic, Python-first measurements for the #180 experiment.

This module intentionally reports observations and deltas rather than judging
code.  It uses only the Python standard library so the experiment can be run
against a clean checkout without changing the runtime dependency surface.
"""

from __future__ import annotations

import ast
import fnmatch
import hashlib
import io
import json
import os
import platform
import re
import subprocess
import sys
import tarfile
import tokenize
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping, Protocol, Sequence

from .factors import FACTOR_VERSION, compare_factors, measure_factors


ANALYZER_VERSION = "0.3.4"
REPORT_SCHEMA = "qca/report/v1"
SOURCE_CLASSES = (
    "production",
    "tests",
    "tooling/scripts",
    "experimental/lab",
    "generated/runtime",
    "vendored/minified",
    "docs/configuration",
    "unknown",
)
_PRODUCTION_TEST_CLASSES = ("production", "tests")
_HUNK_RE = re.compile(
    r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@"
)
_GENERATED_MARKERS = (
    "generated file",
    "generated by",
    "do not edit",
    "automatically generated",
)
_VENDOR_MARKERS = ("vendor", "vendored", "third_party", "third-party", "node_modules")


class AnalysisError(RuntimeError):
    """Raised when the requested source or revision cannot be analyzed."""


@dataclass(frozen=True)
class AnalyzerConfig:
    """Explicit source and exclusion policy carried into every report."""

    include_roots: tuple[str, ...] = (".",)
    excluded_globs: tuple[str, ...] = ()
    languages: tuple[str, ...] = ()
    generated_markers: tuple[str, ...] = _GENERATED_MARKERS
    vendor_markers: tuple[str, ...] = _VENDOR_MARKERS
    lab_roots: tuple[str, ...] = ("lab",)

    def canonical(self) -> dict[str, list[str]]:
        """Return sorted JSON-compatible policy data for hashing and display."""

        return {
            "include_roots": sorted(self.include_roots),
            "excluded_globs": sorted(self.excluded_globs),
            "languages": sorted(self.languages),
            "generated_markers": sorted(self.generated_markers),
            "vendor_markers": sorted(self.vendor_markers),
            "lab_roots": sorted(self.lab_roots),
        }


@dataclass(frozen=True)
class SourceFile:
    path: str
    source_class: str
    language: str
    included: bool
    size_bytes: int


@dataclass(frozen=True)
class CallableMetrics:
    path: str
    qualified_name: str
    start_line: int
    end_line: int
    logical_loc: int
    cyclomatic_complexity: int
    decision_count: int
    max_nesting: int


@dataclass
class SnapshotMetrics:
    file_count: int = 0
    included_file_count: int = 0
    raw_loc: int = 0
    effective_loc: int = 0
    logical_loc: int = 0
    decision_burden: int = 0
    by_class: dict[str, dict[str, int]] = field(default_factory=dict)
    callables: list[CallableMetrics] = field(default_factory=list)
    import_edges: list[str] = field(default_factory=list)
    public_symbols: list[str] = field(default_factory=list)
    unsupported_files: list[str] = field(default_factory=list)
    syntax_errors: list[dict[str, str]] = field(default_factory=list)
    production_test_split: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class DiffFile:
    path: str
    added_lines: int
    deleted_lines: int
    changed_new_lines: tuple[int, ...] = ()
    changed_old_lines: tuple[int, ...] = ()


@dataclass
class DiffMetrics:
    changed_files: list[str] = field(default_factory=list)
    file_changes: list[dict[str, Any]] = field(default_factory=list)
    included_changed_files: list[str] = field(default_factory=list)
    changed_directory_count: int = 0
    added_lines: int = 0
    deleted_lines: int = 0
    churn: int = 0
    included_added_lines: int = 0
    included_deleted_lines: int = 0
    included_churn: int = 0
    changed_by_class: dict[str, dict[str, int]] = field(default_factory=dict)
    production_test_split: dict[str, Any] = field(default_factory=dict)
    changed_callables: list[dict[str, Any]] = field(default_factory=list)
    new_import_edges: list[str] = field(default_factory=list)
    removed_import_edges: list[str] = field(default_factory=list)
    public_symbols_added: list[str] = field(default_factory=list)
    public_symbols_removed: list[str] = field(default_factory=list)
    decision_burden_delta: int = 0
    review_targets: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class ReportIdentity:
    analyzer_version: str
    schema: str
    mode: str
    base_sha: str | None
    head_sha: str | None
    working_tree_digest: str | None
    analyzed_path: str
    config_hash: str
    exclusion_hash: str
    tool_versions: dict[str, str]


@dataclass
class Report:
    identity: ReportIdentity
    source_inventory: list[SourceFile]
    head: SnapshotMetrics
    base: SnapshotMetrics | None = None
    diff: DiffMetrics | None = None
    observations: list[dict[str, Any]] = field(default_factory=list)
    factors: dict[str, dict[str, Any]] = field(default_factory=dict)
    factor_version: str = FACTOR_VERSION
    configuration: dict[str, list[str]] = field(default_factory=dict)


class _SourceReader(Protocol):
    def files(self) -> list[str]:
        ...

    def read_text(self, relative_path: str) -> str:
        ...


class _MappingReader:
    """Read an explicit path → text mapping with no Git dependency."""

    def __init__(self, sources: Mapping[str, str]) -> None:
        self._sources = {path.replace("\\", "/"): text for path, text in sources.items()}

    def files(self) -> list[str]:
        return sorted(self._sources)

    def read_text(self, relative_path: str) -> str:
        return self._sources.get(relative_path.replace("\\", "/"), "")


@dataclass(frozen=True)
class _ResolvedTree:
    root: Path
    repo_root: Path | None
    scope_rel: str
    ref: str | None
    sha: str | None


class _TreeReader:
    """Read either the working tree or an immutable Git revision."""

    def __init__(self, tree: _ResolvedTree) -> None:
        self.tree = tree
        self._ref_contents: dict[str, str] | None = None

    def files(self) -> list[str]:
        if self.tree.ref is None:
            root = self.tree.root
            if root.is_file():
                return [root.name]
            paths: list[str] = []
            for path in root.rglob("*"):
                if not path.is_file():
                    continue
                if ".git" in path.parts or "__pycache__" in path.parts:
                    continue
                paths.append(path.relative_to(root).as_posix())
            return sorted(paths)

        prefix = [] if self.tree.scope_rel in {"", "."} else [self.tree.scope_rel]
        output = _git(
            ["ls-tree", "-r", "--name-only", self.tree.ref, "--", *prefix],
            cwd=self.tree.repo_root,
        )
        paths = []
        scope = PurePosixPath(self.tree.scope_rel) if self.tree.scope_rel not in {"", "."} else None
        for line in output.splitlines():
            repo_path = PurePosixPath(line.strip())
            if scope is None:
                relative = repo_path
            elif self.tree.root.is_file():
                if repo_path != scope:
                    continue
                relative = PurePosixPath(repo_path.name)
            else:
                try:
                    relative = repo_path.relative_to(scope)
                except ValueError:
                    continue
            paths.append(relative.as_posix())
        return sorted(paths)

    def read_text(self, relative_path: str) -> str:
        if self.tree.ref is None:
            path = self.tree.root if self.tree.root.is_file() else self.tree.root / relative_path
            try:
                return path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                return path.read_bytes().decode("utf-8", errors="replace")

        repo_path = PurePosixPath(relative_path)
        if self.tree.scope_rel not in {"", "."}:
            repo_path = PurePosixPath(self.tree.scope_rel) / repo_path
        try:
            if self._ref_contents is None:
                self._ref_contents = self._load_ref_contents()
            relative = relative_path.replace("\\", "/")
            if relative in self._ref_contents:
                return self._ref_contents[relative]
            return _git_bytes(
                ["show", f"{self.tree.ref}:{repo_path.as_posix()}"],
                cwd=self.tree.repo_root,
            ).decode("utf-8", errors="replace")
        except AnalysisError:
            return ""

    def _load_ref_contents(self) -> dict[str, str]:
        """Batch-read one revision so historical backtests avoid one process per file."""

        scope = [] if self.tree.scope_rel in {"", "."} else [self.tree.scope_rel]
        archive = _git_bytes(
            ["archive", "--format=tar", self.tree.ref, "--", *scope],
            cwd=self.tree.repo_root,
        )
        contents: dict[str, str] = {}
        with tarfile.open(fileobj=io.BytesIO(archive), mode="r:") as tar:
            scope_path = PurePosixPath(self.tree.scope_rel)
            for member in tar.getmembers():
                if not member.isfile():
                    continue
                name = PurePosixPath(member.name)
                if self.tree.root.is_file():
                    if name.name != scope_path.name:
                        continue
                    relative = name.name
                elif self.tree.scope_rel in {"", "."}:
                    relative = name.as_posix()
                else:
                    try:
                        relative = name.relative_to(scope_path).as_posix()
                    except ValueError:
                        continue
                extracted = tar.extractfile(member)
                if extracted is not None:
                    contents[relative] = extracted.read().decode("utf-8", errors="replace")
        return contents


def analyze_tree(
    path: str | Path | Sequence[str | Path] = ".",
    *,
    ref: str | None = None,
    config: AnalyzerConfig | None = None,
) -> Report:
    """Measure files, directories, or one Git revision.

    Git is required only when ``ref`` is set.  Otherwise any file or directory
    of text can be measured, including trees that are not repositories.
    """

    paths = _as_paths(path)
    policy = config or AnalyzerConfig()
    if ref is not None:
        if len(paths) != 1:
            raise AnalysisError("revision mode requires a single path")
        tree = _resolve_tree(paths[0], ref=ref)
        reader: _SourceReader = _TreeReader(tree)
        inventory = _inventory(reader, policy)
        head = _measure_snapshot(reader, inventory)
        identity = _identity(
            mode="tree",
            analyzed_path=tree.scope_rel,
            head_sha=tree.sha,
            repo_root=tree.repo_root,
            config=policy,
            working_tree_digest=None,
        )
        return Report(
            identity=identity,
            source_inventory=inventory,
            head=head,
            observations=_observations(head, None, None),
            factors=measure_factors(_factor_sources(reader, inventory)),
            configuration=policy.canonical(),
        )
    analyzed_path, sources = _sources_from_paths(paths)
    return analyze_sources(sources, config=policy, analyzed_path=analyzed_path)


def analyze_sources(
    sources: Mapping[str, str],
    *,
    config: AnalyzerConfig | None = None,
    analyzed_path: str = ".",
) -> Report:
    """Measure an explicit path → text mapping. Git is not required."""

    policy = config or AnalyzerConfig()
    reader = _MappingReader(sources)
    inventory = _inventory(reader, policy)
    head = _measure_snapshot(reader, inventory)
    identity = _identity(
        mode="tree",
        analyzed_path=analyzed_path,
        head_sha=None,
        repo_root=None,
        config=policy,
        working_tree_digest=_sources_digest(reader, inventory),
    )
    return Report(
        identity=identity,
        source_inventory=inventory,
        head=head,
        observations=_observations(head, None, None),
        factors=measure_factors(_factor_sources(reader, inventory)),
        configuration=policy.canonical(),
    )


def analyze_diff(
    base: str,
    head: str,
    *,
    path: str | Path = ".",
    config: AnalyzerConfig | None = None,
) -> Report:
    """Measure a reproducible base→head Git change."""

    policy = config or AnalyzerConfig()
    root_path = Path(path)
    repo_root = _find_repo_root(root_path)
    if repo_root is None:
        raise AnalysisError("diff mode requires a path inside a Git repository")
    base_tree = _resolve_tree(root_path, ref=base, repo_root=repo_root)
    head_tree = _resolve_tree(root_path, ref=head, repo_root=repo_root)
    base_reader = _TreeReader(base_tree)
    head_reader = _TreeReader(head_tree)
    base_inventory = _inventory(base_reader, policy)
    head_inventory = _inventory(head_reader, policy)
    base_snapshot = _measure_snapshot(base_reader, base_inventory)
    head_snapshot = _measure_snapshot(head_reader, head_inventory)
    file_diffs = _read_git_diff(
        repo_root=repo_root,
        base_sha=base_tree.sha or base,
        head_sha=head_tree.sha or head,
        scope_rel=head_tree.scope_rel,
    )
    file_diffs = _scope_file_diffs(file_diffs, head_tree.scope_rel)
    diff = _derive_diff(base_snapshot, head_snapshot, base_inventory, head_inventory, file_diffs)
    identity = _identity(
        mode="diff",
        analyzed_path=head_tree.scope_rel,
        head_sha=head_tree.sha,
        repo_root=head_tree.repo_root,
        base_sha=base_tree.sha,
        config=policy,
        working_tree_digest=None,
    )
    return Report(
        identity=identity,
        source_inventory=head_inventory,
        head=head_snapshot,
        base=base_snapshot,
        diff=diff,
        observations=_observations(head_snapshot, base_snapshot, diff),
        factors=compare_factors(
            measure_factors(_factor_sources(base_reader, base_inventory)),
            measure_factors(_factor_sources(head_reader, head_inventory)),
            set(diff.changed_files),
        ),
        configuration=policy.canonical(),
    )


def _factor_sources(reader: _SourceReader, inventory: list[SourceFile]) -> dict[str, str]:
    return {
        item.path: reader.read_text(item.path)
        for item in inventory
        if item.included and item.language == "python"
    }


def _snapshot_production_test_markdown(split: dict[str, Any]) -> list[str]:
    if not split:
        return []
    files = split["files"]
    raw = split["raw_loc"]
    effective = split["effective_loc"]
    return [
        "",
        "### Production vs tests",
        "",
        "Denominator is `production+tests`. Core snapshot LOC still includes `tooling/scripts` and `experimental/lab`.",
        "",
        "| Class | Files | Raw LOC | Raw share | Effective Python LOC | Effective share |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
        (
            f"| `production` | {files['production']} | {raw['production']} | "
            f"{format_share_permille(raw['production_share_permille'])} | {effective['production']} | "
            f"{format_share_permille(effective['production_share_permille'])} |"
        ),
        (
            f"| `tests` | {files['tests']} | {raw['tests']} | "
            f"{format_share_permille(raw['tests_share_permille'])} | {effective['tests']} | "
            f"{format_share_permille(effective['tests_share_permille'])} |"
        ),
        (
            f"| total | {files['total']} | {raw['total']} | "
            f"{format_share_permille(_share_permille(raw['total'], raw['total']))} | {effective['total']} | "
            f"{format_share_permille(_share_permille(effective['total'], effective['total']))} |"
        ),
    ]


def _diff_line_split_row(label: str, side: dict[str, int], added_share: int | None, net_share: int | None) -> str:
    return (
        f"| {label} | {side['files']} | {side['added_lines']} | {side['deleted_lines']} | "
        f"{side['net_lines']} | {format_share_permille(added_share)} | {format_share_permille(net_share)} |"
    )


def _diff_production_test_markdown(split: dict[str, Any]) -> list[str]:
    if not split:
        return []
    all_lines = split["all_lines"]
    python = split["python"]
    return [
        "",
        "### Production vs tests",
        "",
        production_test_split_summary(split),
        "",
        "Core churn still includes `tooling/scripts` and `experimental/lab`. Docs are a separate class.",
        "",
        "| Class | Files | Added | Deleted | Net | Added share | Net share |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        _diff_line_split_row(
            "`production` all lines",
            all_lines["production"],
            all_lines["production_added_share_permille"],
            all_lines["production_net_share_permille"],
        ),
        _diff_line_split_row(
            "`tests` all lines",
            all_lines["tests"],
            all_lines["tests_added_share_permille"],
            all_lines["tests_net_share_permille"],
        ),
        _diff_line_split_row(
            "`production` Python",
            python["production"],
            python["production_added_share_permille"],
            python["production_net_share_permille"],
        ),
        _diff_line_split_row(
            "`tests` Python",
            python["tests"],
            python["tests_added_share_permille"],
            python["tests_net_share_permille"],
        ),
    ]


def report_to_dict(report: Report) -> dict[str, Any]:
    """Return a stable JSON-compatible report representation."""

    payload = asdict(report)
    payload["identity"]["report_schema"] = REPORT_SCHEMA
    payload["source_inventory"] = sorted(
        payload["source_inventory"], key=lambda item: item["path"]
    )
    payload["head"]["callables"] = sorted(
        payload["head"]["callables"], key=lambda item: (item["path"], item["qualified_name"])
    )
    if payload.get("base"):
        payload["base"]["callables"] = sorted(
            payload["base"]["callables"], key=lambda item: (item["path"], item["qualified_name"])
        )
    return _sort_json_value(payload)


def render_markdown(report: Report) -> str:
    """Render a concise human-readable summary without quality grades."""

    payload = report_to_dict(report)
    identity = payload["identity"]
    lines = [
        "# Quantitative Change Analysis",
        "",
        f"- schema: `{identity['report_schema']}`",
        f"- mode: `{identity['mode']}`",
        f"- analyzer: `{identity['analyzer_version']}`",
        f"- base: `{identity['base_sha'] or '(none)'}`",
        f"- head: `{identity['head_sha'] or '(working tree)'}`",
        f"- working-tree digest: `{identity['working_tree_digest'] or '(none)'}`",
        f"- path: `{identity['analyzed_path']}`",
        "",
        "## Snapshot",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| files | {payload['head']['file_count']} |",
        f"| included files | {payload['head']['included_file_count']} |",
        f"| raw LOC | {payload['head']['raw_loc']} |",
        f"| effective LOC | {payload['head']['effective_loc']} |",
        f"| logical LOC | {payload['head']['logical_loc']} |",
        f"| decision burden | {payload['head']['decision_burden']} |",
        f"| callables | {len(payload['head']['callables'])} |",
        f"| import edges | {len(payload['head']['import_edges'])} |",
        f"| public symbols | {len(payload['head']['public_symbols'])} |",
    ]
    lines.extend(
        [
            "",
            "### Snapshot by source class",
            "",
            "| Source class | Files | All raw LOC | Core Python effective LOC |",
            "| --- | ---: | ---: | ---: |",
        ]
    )
    for source_class, values in payload["head"]["by_class"].items():
        if values["files"]:
            lines.append(
                f"| `{source_class}` | {values['files']} | {values['raw_loc']} | {values['effective_loc']} |"
            )
    lines.extend(_snapshot_production_test_markdown(payload["head"].get("production_test_split") or {}))
    if payload["diff"] is not None:
        diff = payload["diff"]
        lines.extend(
            [
                "",
                "## Change",
                "",
                "| Metric | Value |",
                "| --- | ---: |",
                f"| changed files | {len(diff['changed_files'])} |",
                f"| included changed files | {len(diff['included_changed_files'])} |",
                f"| changed directories | {diff['changed_directory_count']} |",
                f"| added lines | {diff['added_lines']} |",
                f"| deleted lines | {diff['deleted_lines']} |",
                f"| churn | {diff['churn']} |",
                f"| included added lines | {diff['included_added_lines']} |",
                f"| included deleted lines | {diff['included_deleted_lines']} |",
                f"| included churn | {diff['included_churn']} |",
                f"| decision burden delta | {diff['decision_burden_delta']:+d} |",
                f"| new import edges | {len(diff['new_import_edges'])} |",
                f"| public symbols added | {len(diff['public_symbols_added'])} |",
                f"| public symbols removed | {len(diff['public_symbols_removed'])} |",
                "",
                "### Changed files",
                "",
                "| Path | Source class | Core measured | Added | Deleted |",
                "| --- | --- | :---: | ---: | ---: |",
            ]
        )
        for change in diff["file_changes"]:
            lines.append(
                f"| `{change['path']}` | `{change['source_class']}` | "
                f"{'yes' if change['included'] else 'no'} | {change['added_lines']} | {change['deleted_lines']} |"
            )
        lines.extend(
            [
                "",
                "### Changed by source class",
                "",
                "| Source class | Files | Added | Deleted |",
                "| --- | ---: | ---: | ---: |",
            ]
        )
        for source_class, values in diff["changed_by_class"].items():
            if values["files"]:
                lines.append(
                    f"| `{source_class}` | {values['files']} | {values['added_lines']} | {values['deleted_lines']} |"
                )
        lines.extend(_diff_production_test_markdown(diff.get("production_test_split") or {}))
        targets = diff["review_targets"]
        lines.extend(
            [
                "",
                "### Review targets",
                "",
                "These deterministic prompts identify evidence to inspect; they are not quality grades or gates.",
                "",
            ]
        )
        for target in targets[:25]:
            if target["kind"] == "callable":
                label = f"`{target['path']}::{target['qualified_name']}`"
            elif target["kind"] == "callable_group":
                label = f"callables in `{target['path']}`"
            elif target["kind"] == "dependency":
                label = f"dependency `{target['edge']}`"
            elif target["kind"] == "public_surface":
                label = f"public symbol `{target['symbol']}`"
            elif target["kind"] == "file":
                label = f"file `{target['path']}`"
            else:
                label = f"syntax in `{target['path']}`"
            lines.append(f"- inspect {label}: {', '.join(target['reasons'])}")
        if len(targets) > 25:
            lines.append(f"- ... {len(targets) - 25} additional targets are in the JSON report")
    lines.extend(["", "## Factors", ""])
    lines.append("Static findings are refactoring candidates. Runtime evidence is reported separately.")
    for name, factor in payload["factors"].items():
        lines.extend(["", f"### {name}", "", f"Status: `{factor['status']}`", ""])
        if factor["metrics"]:
            lines.extend(["| Measurement | Head | Delta |", "| --- | ---: | ---: |"])
            for metric, value in factor["metrics"].items():
                delta = factor.get("delta", {}).get(metric)
                lines.append(f"| {metric} | {value} | {delta if delta is not None else '—'} |")
            lines.append("")
        for item in factor["findings"][:8]:
            lines.append(
                f"- `{item.get('path', '')}:{item.get('line', '')}`: {item.get('message', '')}"
            )
        if len(factor["findings"]) > 8:
            lines.append(f"- {len(factor['findings']) - 8} more candidates in JSON/HTML.")
        lines.append("")
        lines.extend(f"- Limit: {limit}" for limit in factor["limitations"])
        if factor.get("verification"):
            lines.extend(["", "Verification:", "", "```json", json.dumps(factor["verification"], indent=2), "```"])
    lines.extend(["", "## Observations", ""])
    for observation in payload["observations"]:
        lines.append(f"- `{observation['id']}`: {json.dumps(observation['value'], sort_keys=True)}")
    lines.append("")
    return "\n".join(lines)


def _resolve_tree(
    path: Path,
    *,
    ref: str | None,
    repo_root: Path | None = None,
) -> _ResolvedTree:
    absolute = path.resolve()
    if absolute.is_file():
        scope_path = absolute
        working_root = absolute.parent
    else:
        scope_path = absolute
        working_root = absolute
    discovered = repo_root or _find_repo_root(working_root)
    if ref is None:
        scope_rel = _scope_relative(scope_path, discovered) if discovered else "."
        return _ResolvedTree(
            root=scope_path,
            repo_root=discovered,
            scope_rel=scope_rel,
            ref=None,
            sha=None,
        )
    if discovered is None:
        raise AnalysisError(f"revision mode requires a Git repository: {path}")
    scope_rel = _scope_relative(scope_path, discovered)
    sha = _resolve_ref(ref, discovered)
    return _ResolvedTree(
        root=scope_path,
        repo_root=discovered,
        scope_rel=scope_rel,
        ref=sha,
        sha=sha,
    )


def _scope_relative(path: Path, repo_root: Path | None) -> str:
    if repo_root is None:
        return "."
    try:
        relative = path.resolve().relative_to(repo_root.resolve())
    except ValueError as exc:
        raise AnalysisError(f"path is outside repository: {path}") from exc
    return relative.as_posix() or "."


def _find_repo_root(path: Path) -> Path | None:
    cwd = path if path.is_dir() else path.parent
    try:
        output = _git(["rev-parse", "--show-toplevel"], cwd=cwd)
    except AnalysisError:
        return None
    return Path(output.strip()).resolve()


def _resolve_ref(ref: str, repo_root: Path | None) -> str | None:
    if repo_root is None:
        return None
    return _git(["rev-parse", f"{ref}^{{commit}}"], cwd=repo_root).strip()


def _git(args: Sequence[str], *, cwd: Path | None) -> str:
    if cwd is None:
        raise AnalysisError("Git command has no repository working directory")
    completed = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0:
        detail = completed.stderr.strip() or "unknown Git error"
        raise AnalysisError(f"git {' '.join(args)} failed: {detail}")
    return completed.stdout


def _git_bytes(args: Sequence[str], *, cwd: Path | None) -> bytes:
    """Run Git without decoding file contents as UTF-8 first."""

    if cwd is None:
        raise AnalysisError("Git command has no repository working directory")
    completed = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode != 0:
        detail = completed.stderr.decode("utf-8", errors="replace").strip() or "unknown Git error"
        raise AnalysisError(f"git {' '.join(args)} failed: {detail}")
    return completed.stdout


def _inventory(reader: _SourceReader, config: AnalyzerConfig) -> list[SourceFile]:
    inventory: list[SourceFile] = []
    allowed_languages = set(config.languages)
    for relative in reader.files():
        language = _language_for(relative)
        if allowed_languages and language not in allowed_languages:
            continue
        text = reader.read_text(relative)
        source_class = classify_source(relative, text, config)
        inventory.append(
            SourceFile(
                path=relative,
                source_class=source_class,
                language=language,
                included=(
                    _under_include_root(relative, config.include_roots)
                    and _included(relative, source_class, config)
                ),
                size_bytes=len(text.encode("utf-8")),
            )
        )
    return sorted(inventory, key=lambda item: item.path)


def _under_include_root(path: str, roots: tuple[str, ...]) -> bool:
    normalized = path.replace("\\", "/").strip("/")
    if not roots or "." in roots:
        return True
    for root in roots:
        prefix = root.replace("\\", "/").strip("/").rstrip("/")
        if prefix in {"", "."} or normalized == prefix or normalized.startswith(prefix + "/"):
            return True
    return False


def classify_source(path: str, text: str, config: AnalyzerConfig | None = None) -> str:
    """Classify a path using explicit precedence and repository-neutral names."""

    policy = config or AnalyzerConfig()
    normalized = path.replace("\\", "/")
    lower = normalized.lower()
    segments = set(PurePosixPath(lower).parts)
    first_lines = "\n".join(text.splitlines()[:12]).lower()
    if "__pycache__" in segments or "runtime" in segments:
        return "generated/runtime"
    if any(marker.lower() in lower for marker in policy.vendor_markers):
        return "vendored/minified"
    if ".min." in lower or lower.endswith(".min.js"):
        return "vendored/minified"
    if any(marker.lower() in first_lines for marker in policy.generated_markers):
        return "generated/runtime"
    if "tests" in segments or PurePosixPath(lower).name.startswith("test_"):
        return "tests"
    if any(root.lower() in segments for root in policy.lab_roots) or lower.startswith("lab/"):
        return "experimental/lab"
    if "scripts" in segments or "tools" in segments or ".github" in segments:
        return "tooling/scripts"
    if "evidence" in segments:
        if PurePosixPath(lower).suffix in {".py", ".sh", ".ps1"}:
            return "tooling/scripts"
        return "generated/runtime"
    if lower.startswith("docs/") or lower.startswith("documentation/"):
        return "docs/configuration"
    if PurePosixPath(lower).suffix in {
        ".md",
        ".rst",
        ".json",
        ".yaml",
        ".yml",
        ".toml",
        ".ini",
    }:
        return "docs/configuration"
    if segments:
        return "production"
    return "unknown"


def _included(path: str, source_class: str, config: AnalyzerConfig) -> bool:
    if source_class not in {"production", "tests", "tooling/scripts", "experimental/lab"}:
        return False
    normalized = path.replace("\\", "/")
    return not any(
        fnmatch.fnmatch(normalized, pattern) or fnmatch.fnmatch(Path(normalized).name, pattern)
        for pattern in config.excluded_globs
    )


def _language_for(path: str) -> str:
    suffix = PurePosixPath(path).suffix.lower()
    return {
        ".py": "python",
        ".pyi": "python",
        ".js": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".jsx": "javascript",
        ".html": "html",
        ".css": "css",
        ".go": "go",
        ".rs": "rust",
        ".c": "c",
        ".h": "c",
        ".cpp": "cpp",
        ".java": "java",
    }.get(suffix, "other")


def format_share_permille(value: int | None) -> str:
    """Render a 0-1000 permille share as a one-decimal percentage, or n/a."""

    if value is None:
        return "n/a"
    return f"{value / 10:.1f}%"


def _share_permille(part: int, total: int) -> int | None:
    """Return part/total as rounded permille, or None when total is 0."""

    if total == 0:
        return None
    if total < 0:
        part = -part
        total = -total
    return (part * 1000 + total // 2) // total


def _loc_share_block(production: int, tests: int) -> dict[str, int | None]:
    total = production + tests
    return {
        "production": production,
        "tests": tests,
        "total": total,
        "production_share_permille": _share_permille(production, total),
        "tests_share_permille": _share_permille(tests, total),
    }


def _line_counts(files: int, added_lines: int, deleted_lines: int) -> dict[str, int]:
    return {
        "files": files,
        "added_lines": added_lines,
        "deleted_lines": deleted_lines,
        "net_lines": added_lines - deleted_lines,
    }


def _diff_line_split(sides: dict[str, dict[str, int]]) -> dict[str, Any]:
    production = sides["production"]
    tests = sides["tests"]
    total = _line_counts(
        production["files"] + tests["files"],
        production["added_lines"] + tests["added_lines"],
        production["deleted_lines"] + tests["deleted_lines"],
    )
    return {
        "production": production,
        "tests": tests,
        "total": total,
        "production_added_share_permille": _share_permille(
            production["added_lines"], total["added_lines"]
        ),
        "tests_added_share_permille": _share_permille(tests["added_lines"], total["added_lines"]),
        "production_net_share_permille": _share_permille(production["net_lines"], total["net_lines"]),
        "tests_net_share_permille": _share_permille(tests["net_lines"], total["net_lines"]),
    }


def snapshot_production_test_split(by_class: dict[str, dict[str, int]]) -> dict[str, Any]:
    """Derive production vs tests size shares from a snapshot class table."""

    production = by_class.get("production") or {"files": 0, "raw_loc": 0, "effective_loc": 0}
    tests = by_class.get("tests") or {"files": 0, "raw_loc": 0, "effective_loc": 0}
    return {
        "classes": list(_PRODUCTION_TEST_CLASSES),
        "denominator": "production+tests",
        "files": _loc_share_block(production.get("files", 0), tests.get("files", 0)),
        "raw_loc": _loc_share_block(production.get("raw_loc", 0), tests.get("raw_loc", 0)),
        "effective_loc": _loc_share_block(
            production.get("effective_loc", 0), tests.get("effective_loc", 0)
        ),
    }


def diff_production_test_split(file_changes: list[dict[str, Any]]) -> dict[str, Any]:
    """Derive production vs tests added/deleted/net shares, all-line and Python."""

    all_sides = {
        name: {"files": 0, "added_lines": 0, "deleted_lines": 0} for name in _PRODUCTION_TEST_CLASSES
    }
    python_sides = {
        name: {"files": 0, "added_lines": 0, "deleted_lines": 0} for name in _PRODUCTION_TEST_CLASSES
    }
    for item in file_changes:
        source_class = item.get("source_class")
        if source_class not in all_sides:
            continue
        all_sides[source_class]["files"] += 1
        all_sides[source_class]["added_lines"] += int(item.get("added_lines", 0))
        all_sides[source_class]["deleted_lines"] += int(item.get("deleted_lines", 0))
        if item.get("language") == "python":
            python_sides[source_class]["files"] += 1
            python_sides[source_class]["added_lines"] += int(item.get("added_lines", 0))
            python_sides[source_class]["deleted_lines"] += int(item.get("deleted_lines", 0))
    return {
        "classes": list(_PRODUCTION_TEST_CLASSES),
        "denominator": "production+tests",
        "all_lines": _diff_line_split(
            {
                name: _line_counts(values["files"], values["added_lines"], values["deleted_lines"])
                for name, values in all_sides.items()
            }
        ),
        "python": _diff_line_split(
            {
                name: _line_counts(values["files"], values["added_lines"], values["deleted_lines"])
                for name, values in python_sides.items()
            }
        ),
    }


def production_test_split_summary(split: dict[str, Any]) -> str:
    """One-line production vs tests observation for Markdown and backtests."""

    python = split["python"]
    all_lines = split["all_lines"]
    return (
        "Production vs tests (denominator production+tests): "
        f"Python net production {python['production']['net_lines']} "
        f"({format_share_permille(python['production_net_share_permille'])}), "
        f"tests {python['tests']['net_lines']} "
        f"({format_share_permille(python['tests_net_share_permille'])}); "
        f"all-line net production {all_lines['production']['net_lines']} "
        f"({format_share_permille(all_lines['production_net_share_permille'])}), "
        f"tests {all_lines['tests']['net_lines']} "
        f"({format_share_permille(all_lines['tests_net_share_permille'])})."
    )


def _measure_snapshot(reader: _SourceReader, inventory: list[SourceFile]) -> SnapshotMetrics:
    metrics = SnapshotMetrics(
        file_count=len(inventory),
        included_file_count=sum(item.included for item in inventory),
        by_class={source_class: {"files": 0, "raw_loc": 0, "effective_loc": 0} for source_class in SOURCE_CLASSES},
    )
    for item in inventory:
        text = reader.read_text(item.path)
        raw_loc = len(text.splitlines())
        bucket = metrics.by_class.setdefault(
            item.source_class,
            {"files": 0, "raw_loc": 0, "effective_loc": 0},
        )
        bucket["files"] += 1
        bucket["raw_loc"] += raw_loc
        if not item.included:
            continue
        effective = _effective_loc(text) if item.language == "python" else 0
        bucket["effective_loc"] += effective
        metrics.raw_loc += raw_loc
        metrics.effective_loc += effective
        if item.language != "python":
            metrics.unsupported_files.append(item.path)
            continue
        parsed = _measure_python(text, item.path)
        metrics.logical_loc += parsed["logical_loc"]
        bucket["logical_loc"] = bucket.get("logical_loc", 0) + parsed["logical_loc"]
        metrics.callables.extend(parsed["callables"])
        metrics.import_edges.extend(parsed["import_edges"])
        metrics.public_symbols.extend(parsed["public_symbols"])
        if parsed["syntax_error"]:
            metrics.syntax_errors.append(parsed["syntax_error"])
    metrics.callables.sort(key=lambda item: (item.path, item.qualified_name, item.start_line))
    metrics.import_edges = sorted(set(metrics.import_edges))
    metrics.public_symbols = sorted(set(metrics.public_symbols))
    metrics.unsupported_files.sort()
    metrics.syntax_errors.sort(key=lambda item: item["path"])
    metrics.decision_burden = sum(
        max(0, item.cyclomatic_complexity - 1) for item in metrics.callables
    )
    for bucket in metrics.by_class.values():
        bucket.setdefault("logical_loc", 0)
    metrics.production_test_split = snapshot_production_test_split(metrics.by_class)
    return metrics


def _measure_python(text: str, path: str) -> dict[str, Any]:
    try:
        tree = ast.parse(text, filename=path)
    except SyntaxError as exc:
        return {
            "logical_loc": _effective_loc(text),
            "callables": [],
            "import_edges": [],
            "public_symbols": [],
            "syntax_error": {"path": path, "message": str(exc)},
        }
    collector = _CallableCollector(path)
    collector.visit(tree)
    public_symbols = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith("_"):
                public_symbols.append(f"{path}:{node.name}")
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            names = _assigned_names(node)
            public_symbols.extend(f"{path}:{name}" for name in names if not name.startswith("_"))
    import_edges = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            import_edges.extend(f"{path}->{alias.name}" for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            module = "." * node.level + (node.module or "")
            import_edges.extend(f"{path}->{module}" for _alias in node.names)
    return {
        "logical_loc": sum(isinstance(node, ast.stmt) for node in ast.walk(tree)),
        "callables": collector.callables,
        "import_edges": import_edges,
        "public_symbols": public_symbols,
        "syntax_error": None,
    }


class _CallableCollector(ast.NodeVisitor):
    def __init__(self, path: str) -> None:
        self.path = path
        self.scope: list[str] = []
        self.callables: list[CallableMetrics] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._record(node, node.name)
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._record(node, node.name)
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_Lambda(self, node: ast.Lambda) -> None:
        self._record(node, f"<lambda>@{getattr(node, 'lineno', 0)}")
        self.generic_visit(node)

    def _record(self, node: ast.AST, name: str) -> None:
        start = int(getattr(node, "lineno", 0))
        end = int(getattr(node, "end_lineno", start))
        decisions, nesting, logical_loc = _callable_shape(node)
        qualified = ".".join([*self.scope, name])
        self.callables.append(
            CallableMetrics(
                path=self.path,
                qualified_name=qualified,
                start_line=start,
                end_line=end,
                logical_loc=logical_loc,
                cyclomatic_complexity=decisions + 1,
                decision_count=decisions,
                max_nesting=nesting,
            )
        )


def _callable_shape(root: ast.AST) -> tuple[int, int, int]:
    decisions = 0
    max_depth = 0
    statement_count = 0
    nested_types = (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)
    control_types = (ast.If, ast.For, ast.AsyncFor, ast.While, ast.Try, ast.With, ast.AsyncWith, ast.Match)

    def visit(node: ast.AST, depth: int, *, is_root: bool = False) -> None:
        nonlocal decisions, max_depth, statement_count
        if not is_root and isinstance(node, nested_types):
            return
        if isinstance(node, ast.stmt):
            statement_count += 1
        next_depth = depth + 1 if isinstance(node, control_types) else depth
        max_depth = max(max_depth, next_depth)
        if isinstance(node, (ast.If, ast.For, ast.AsyncFor, ast.While, ast.ExceptHandler, ast.IfExp, ast.Match)):
            decisions += 1
        if isinstance(node, ast.BoolOp):
            decisions += max(0, len(node.values) - 1)
        if isinstance(node, ast.Match):
            decisions += max(0, len(node.cases) - 1)
        for child in ast.iter_child_nodes(node):
            visit(child, next_depth)

    visit(root, 0, is_root=True)
    return decisions, max_depth, statement_count


def _assigned_names(node: ast.AST) -> list[str]:
    targets = node.targets if isinstance(node, ast.Assign) else [node.target]
    names: list[str] = []
    for target in targets:
        for child in ast.walk(target):
            if isinstance(child, ast.Name):
                names.append(child.id)
    return sorted(set(names))


def _effective_loc(text: str) -> int:
    lines: set[int] = set()
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        ignored = {tokenize.ENCODING, tokenize.ENDMARKER, tokenize.NL, tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT, tokenize.COMMENT}
        for token in tokens:
            if token.type in ignored:
                continue
            lines.update(range(token.start[0], token.end[0] + 1))
    except (tokenize.TokenError, IndentationError):
        for number, line in enumerate(text.splitlines(), start=1):
            if line.strip() and not line.lstrip().startswith("#"):
                lines.add(number)
    return len(lines)


def _read_git_diff(
    *,
    repo_root: Path,
    base_sha: str,
    head_sha: str,
    scope_rel: str,
) -> list[DiffFile]:
    scope = [] if scope_rel in {"", "."} else [scope_rel]
    numstat = _git(
        ["diff", "--no-ext-diff", "--no-renames", "--numstat", base_sha, head_sha, "--", *scope],
        cwd=repo_root,
    )
    stats: dict[str, list[int]] = {}
    for line in numstat.splitlines():
        parts = line.split("\t", 2)
        if len(parts) != 3:
            continue
        added = 0 if parts[0] == "-" else int(parts[0])
        deleted = 0 if parts[1] == "-" else int(parts[1])
        path = _normalize_diff_path(parts[2])
        stats[path] = [added, deleted]

    ranges: dict[str, dict[str, set[int]]] = defaultdict(lambda: {"new": set(), "old": set()})
    unified = _git(
        ["diff", "--no-ext-diff", "--no-renames", "--unified=0", "--no-color", base_sha, head_sha, "--", *scope],
        cwd=repo_root,
    )
    current: str | None = None
    old_path: str | None = None
    old_line = 0
    new_line = 0
    for line in unified.splitlines():
        if line.startswith("--- "):
            header = line[4:]
            old_path = None if header == "/dev/null" else _normalize_diff_path(header)
            continue
        if line.startswith("+++ "):
            header = line[4:]
            new_path = None if header == "/dev/null" else _normalize_diff_path(header)
            current = new_path or old_path
            continue
        match = _HUNK_RE.match(line)
        if match:
            old_line = int(match.group(1))
            new_line = int(match.group(3))
            if current is None:
                current = ""
            continue
        if current is None or not line:
            continue
        if line.startswith("+"):
            if not line.startswith("+++"):
                ranges[current]["new"].add(new_line)
                new_line += 1
        elif line.startswith("-"):
            if not line.startswith("---"):
                ranges[current]["old"].add(old_line)
                old_line += 1
        else:
            old_line += 1
            new_line += 1

    paths = sorted(set(stats) | set(ranges))
    return [
        DiffFile(
            path=path,
            added_lines=stats.get(path, [0, 0])[0],
            deleted_lines=stats.get(path, [0, 0])[1],
            changed_new_lines=tuple(sorted(ranges[path]["new"])),
            changed_old_lines=tuple(sorted(ranges[path]["old"])),
        )
        for path in paths
    ]


def _scope_file_diffs(file_diffs: list[DiffFile], scope_rel: str) -> list[DiffFile]:
    """Align Git's repository-relative paths with a scoped tree inventory."""

    if scope_rel in {"", "."}:
        return file_diffs
    scope = PurePosixPath(scope_rel)
    scoped: list[DiffFile] = []
    for item in file_diffs:
        try:
            relative = PurePosixPath(item.path).relative_to(scope).as_posix()
        except ValueError:
            # Git should only return paths inside the requested scope.  Keep
            # an explicit path if it does not, so the report cannot silently
            # lose a changed file.
            relative = item.path
        scoped.append(
            DiffFile(
                path=relative,
                added_lines=item.added_lines,
                deleted_lines=item.deleted_lines,
                changed_new_lines=item.changed_new_lines,
                changed_old_lines=item.changed_old_lines,
            )
        )
    return scoped


def _normalize_diff_path(value: str) -> str:
    # Git quotes unusual paths when core.quotePath is enabled. v0 keeps the
    # common path form explicit and avoids guessing at a rename's two paths.
    if " => " in value and value.startswith("{"):
        value = value.split(" => ", 1)[1].rstrip("}")
    if value.startswith("a/") or value.startswith("b/"):
        value = value[2:]
    return value


def _derive_diff(
    base: SnapshotMetrics,
    head: SnapshotMetrics,
    base_inventory: list[SourceFile],
    head_inventory: list[SourceFile],
    file_diffs: list[DiffFile],
) -> DiffMetrics:
    base_by_path = {item.path: item for item in base_inventory}
    head_by_path = {item.path: item for item in head_inventory}
    base_classes = {path: item.source_class for path, item in base_by_path.items()}
    head_classes = {path: item.source_class for path, item in head_by_path.items()}
    by_class = {source_class: {"added_lines": 0, "deleted_lines": 0, "files": 0} for source_class in SOURCE_CLASSES}
    included_changed_files: list[str] = []
    included_added_lines = 0
    included_deleted_lines = 0
    file_changes: list[dict[str, Any]] = []
    for file_diff in file_diffs:
        source_class = head_classes.get(file_diff.path, base_classes.get(file_diff.path, "unknown"))
        bucket = by_class.setdefault(source_class, {"added_lines": 0, "deleted_lines": 0, "files": 0})
        bucket["added_lines"] += file_diff.added_lines
        bucket["deleted_lines"] += file_diff.deleted_lines
        bucket["files"] += 1
        source_file = head_by_path.get(file_diff.path) or base_by_path.get(file_diff.path)
        file_changes.append(
            {
                "path": file_diff.path,
                "source_class": source_file.source_class if source_file is not None else "unknown",
                "language": source_file.language if source_file is not None else "other",
                "included": source_file.included if source_file is not None else False,
                "added_lines": file_diff.added_lines,
                "deleted_lines": file_diff.deleted_lines,
            }
        )
        if source_file is not None and source_file.included:
            included_changed_files.append(file_diff.path)
            included_added_lines += file_diff.added_lines
            included_deleted_lines += file_diff.deleted_lines
    changed_callables = _changed_callables(base.callables, head.callables, file_diffs)
    base_edges = set(base.import_edges)
    head_edges = set(head.import_edges)
    base_symbols = set(base.public_symbols)
    head_symbols = set(head.public_symbols)
    new_import_edges = sorted(head_edges - base_edges)
    removed_import_edges = sorted(base_edges - head_edges)
    public_symbols_added = sorted(head_symbols - base_symbols)
    public_symbols_removed = sorted(base_symbols - head_symbols)
    review_targets = _review_targets(
        changed_callables=changed_callables,
        new_import_edges=new_import_edges,
        public_symbols_added=public_symbols_added,
        public_symbols_removed=public_symbols_removed,
        syntax_errors=head.syntax_errors,
        source_by_path={
            path: item.source_class
            for path, item in {**base_by_path, **head_by_path}.items()
        },
        changed_non_python=[
            {
                "path": file_diff.path,
                "language": source_file.language,
                "source_class": source_file.source_class,
            }
            for file_diff in file_diffs
            if (source_file := (head_by_path.get(file_diff.path) or base_by_path.get(file_diff.path)))
            and source_file.language != "python"
        ],
    )
    added = sum(item.added_lines for item in file_diffs)
    deleted = sum(item.deleted_lines for item in file_diffs)
    return DiffMetrics(
        changed_files=[item.path for item in file_diffs],
        file_changes=file_changes,
        included_changed_files=sorted(included_changed_files),
        changed_directory_count=len({str(PurePosixPath(item.path).parent) for item in file_diffs}),
        added_lines=added,
        deleted_lines=deleted,
        churn=added + deleted,
        included_added_lines=included_added_lines,
        included_deleted_lines=included_deleted_lines,
        included_churn=included_added_lines + included_deleted_lines,
        changed_by_class={key: by_class[key] for key in sorted(by_class)},
        production_test_split=diff_production_test_split(file_changes),
        changed_callables=changed_callables,
        new_import_edges=new_import_edges,
        removed_import_edges=removed_import_edges,
        public_symbols_added=public_symbols_added,
        public_symbols_removed=public_symbols_removed,
        decision_burden_delta=head.decision_burden - base.decision_burden,
        review_targets=review_targets,
    )


def _changed_callables(
    base: list[CallableMetrics],
    head: list[CallableMetrics],
    file_diffs: list[DiffFile],
) -> list[dict[str, Any]]:
    base_by_key = {(item.path, item.qualified_name): item for item in base}
    head_by_key = {(item.path, item.qualified_name): item for item in head}
    result = []
    for file_diff in file_diffs:
        old_lines = set(file_diff.changed_old_lines)
        new_lines = set(file_diff.changed_new_lines)
        keys = set()
        for key, item in base_by_key.items():
            if item.path == file_diff.path and old_lines.intersection(range(item.start_line, item.end_line + 1)):
                keys.add(key)
        for key, item in head_by_key.items():
            if item.path == file_diff.path and new_lines.intersection(range(item.start_line, item.end_line + 1)):
                keys.add(key)
        for key in sorted(keys):
            result.append(
                {
                    "path": key[0],
                    "qualified_name": key[1],
                    "before": asdict(base_by_key[key]) if key in base_by_key else None,
                    "after": asdict(head_by_key[key]) if key in head_by_key else None,
                }
            )
    return result


def _review_targets(
    *,
    changed_callables: list[dict[str, Any]],
    new_import_edges: list[str],
    public_symbols_added: list[str],
    public_symbols_removed: list[str],
    syntax_errors: list[dict[str, str]],
    source_by_path: dict[str, str],
    changed_non_python: list[dict[str, str]],
) -> list[dict[str, Any]]:
    """Turn measured deltas into deterministic, inspectable follow-up prompts.

    These are not quality judgements or gates.  They are machine-readable
    pointers an agent or operator can use to choose what to inspect next.
    """

    targets: list[dict[str, Any]] = []
    grouped_callables_by_path: defaultdict[str, list[dict[str, Any]]] = defaultdict(list)
    grouped_callable_reasons: defaultdict[str, set[str]] = defaultdict(set)
    for callable_change in changed_callables:
        before = callable_change.get("before")
        after = callable_change.get("after")
        reasons: list[str] = []
        metric_changed = False
        if before is None:
            reasons.append("callable added")
        elif after is None:
            reasons.append("callable removed")
        else:
            reasons.append("changed lines overlap callable")
            for field_name, label in (
                ("logical_loc", "logical size"),
                ("decision_count", "decision count"),
                ("max_nesting", "maximum nesting"),
            ):
                delta = after[field_name] - before[field_name]
                if delta:
                    metric_changed = True
                    direction = "increased" if delta > 0 else "decreased"
                    reasons.append(f"{label} {direction} by {abs(delta)}")
        grouped_addition = before is None and after is not None
        if (before is not None and after is not None and not metric_changed) or grouped_addition:
            path = callable_change["path"]
            grouped_callables_by_path[path].append(
                {
                    "qualified_name": callable_change["qualified_name"],
                    "before": before,
                    "after": after,
                }
            )
            grouped_callable_reasons[path].add(
                "callables added in this file"
                if grouped_addition
                else "changed lines overlap callables; measured shape unchanged"
            )
            continue
        targets.append(
            {
                "kind": "callable",
                "action": "inspect_callable",
                "path": callable_change["path"],
                "qualified_name": callable_change["qualified_name"],
                "source_class": source_by_path.get(callable_change["path"], "unknown"),
                "reasons": reasons,
                "before": before,
                "after": after,
            }
        )
    for path, callables in sorted(grouped_callables_by_path.items()):
        targets.append(
            {
                "kind": "callable_group",
                "action": "inspect_changed_callables",
                "path": path,
                "source_class": source_by_path.get(path, "unknown"),
                "callables": sorted(callables, key=lambda item: item["qualified_name"]),
                "reasons": sorted(grouped_callable_reasons[path]),
            }
        )
    targets.extend(
        {
            "kind": "dependency",
            "action": "inspect_dependency_edge",
            "edge": edge,
            "reasons": ["new import edge"],
        }
        for edge in new_import_edges
        if not _is_standard_library_edge(edge)
    )
    targets.extend(
        {
            "kind": "public_surface",
            "action": "inspect_public_surface",
            "symbol": symbol,
            "reasons": ["public symbol added"],
        }
        for symbol in public_symbols_added
        if _is_inspectable_public_symbol(symbol)
    )
    targets.extend(
        {
            "kind": "public_surface",
            "action": "inspect_public_surface",
            "symbol": symbol,
            "reasons": ["public symbol removed"],
        }
        for symbol in public_symbols_removed
        if _is_inspectable_public_symbol(symbol)
    )
    targets.extend(
        {
            "kind": "file",
            "action": "inspect_unsupported_file",
            "path": item["path"],
            "language": item["language"],
            "source_class": item["source_class"],
            "reasons": ["changed file has no Python structural analysis"],
        }
        for item in changed_non_python
    )
    targets.extend(
        {
            "kind": "syntax",
            "action": "inspect_syntax_error",
            "path": error["path"],
            "reasons": ["head revision has a syntax error"],
            "message": error["message"],
        }
        for error in syntax_errors
    )
    return sorted(
        targets,
        key=lambda target: (
            target["kind"],
            target.get("path", ""),
            target.get("qualified_name", ""),
            target.get("edge", target.get("symbol", "")),
        ),
    )


def _is_standard_library_edge(edge: str) -> bool:
    """Return whether an import edge points only to Python's standard library."""

    _path, module = edge.split("->", 1)
    module = module.lstrip(".")
    if not module:
        return False
    root = module.split(".", 1)[0]
    return root in getattr(sys, "stdlib_module_names", set())


def _is_inspectable_public_symbol(symbol: str) -> bool:
    """Suppress low-value constant-only prompts while retaining API names."""

    name = symbol.rsplit(":", 1)[-1]
    return not name.isupper()


def _observations(
    head: SnapshotMetrics,
    base: SnapshotMetrics | None,
    diff: DiffMetrics | None,
) -> list[dict[str, Any]]:
    observations: list[dict[str, Any]] = [
        {"id": "snapshot.files", "value": head.file_count},
        {"id": "snapshot.included_files", "value": head.included_file_count},
        {"id": "snapshot.raw_loc", "value": head.raw_loc},
        {"id": "snapshot.effective_loc", "value": head.effective_loc},
        {"id": "snapshot.logical_loc", "value": head.logical_loc},
        {"id": "snapshot.decision_burden", "value": head.decision_burden},
        {"id": "snapshot.unsupported_files", "value": head.unsupported_files},
        {"id": "snapshot.syntax_errors", "value": head.syntax_errors},
        {"id": "snapshot.production_test_split", "value": head.production_test_split},
    ]
    if base is not None and diff is not None:
        observations.extend(
            [
                {"id": "diff.changed_files", "value": diff.changed_files},
                {"id": "diff.included_changed_files", "value": diff.included_changed_files},
                {"id": "diff.changed_directory_count", "value": diff.changed_directory_count},
                {"id": "diff.added_lines", "value": diff.added_lines},
                {"id": "diff.deleted_lines", "value": diff.deleted_lines},
                {"id": "diff.churn", "value": diff.churn},
                {"id": "diff.included_added_lines", "value": diff.included_added_lines},
                {"id": "diff.included_deleted_lines", "value": diff.included_deleted_lines},
                {"id": "diff.included_churn", "value": diff.included_churn},
                {"id": "diff.decision_burden_delta", "value": diff.decision_burden_delta},
                {"id": "diff.new_import_edges", "value": diff.new_import_edges},
                {"id": "diff.public_symbols_added", "value": diff.public_symbols_added},
                {"id": "diff.public_symbols_removed", "value": diff.public_symbols_removed},
                {"id": "diff.production_test_split", "value": diff.production_test_split},
            ]
        )
    return observations


def _identity(
    *,
    mode: str,
    analyzed_path: str,
    head_sha: str | None,
    repo_root: Path | None,
    config: AnalyzerConfig,
    working_tree_digest: str | None,
    base_sha: str | None = None,
) -> ReportIdentity:
    policy_json = _canonical_json(config.canonical())
    return ReportIdentity(
        analyzer_version=ANALYZER_VERSION,
        schema=REPORT_SCHEMA,
        mode=mode,
        base_sha=base_sha,
        head_sha=head_sha,
        working_tree_digest=working_tree_digest,
        analyzed_path=analyzed_path,
        config_hash=_sha256(policy_json),
        exclusion_hash=_sha256(_canonical_json({"excluded_globs": sorted(config.excluded_globs)})),
        tool_versions={
            "python": platform.python_version(),
            "ast": "stdlib",
            "tokenize": "stdlib",
            "git": _git_version(repo_root),
        },
    )


def _git_version(repo_root: Path | None) -> str:
    if repo_root is None:
        return "unavailable"
    try:
        return _git(["--version"], cwd=repo_root).strip()
    except AnalysisError:
        return "unavailable"


def _as_paths(path: str | Path | Sequence[str | Path]) -> tuple[Path, ...]:
    if isinstance(path, (str, Path)):
        return (Path(path),)
    paths = tuple(Path(item) for item in path)
    if not paths:
        raise AnalysisError("analyze requires at least one file or directory")
    return paths


def _read_input_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_bytes().decode("utf-8", errors="replace")


def _iter_input_files(root: Path) -> list[Path]:
    if root.is_file():
        return [root]
    if not root.is_dir():
        raise AnalysisError(f"path does not exist: {root}")
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if ".git" in path.parts or "__pycache__" in path.parts:
            continue
        files.append(path)
    return files


def _sources_from_paths(paths: Sequence[Path]) -> tuple[str, dict[str, str]]:
    resolved: list[Path] = []
    for path in paths:
        absolute = path.expanduser().resolve()
        if not absolute.exists():
            raise AnalysisError(f"path does not exist: {path}")
        resolved.append(absolute)
    analyzed_path = " ".join(path.as_posix() for path in paths)
    if len(resolved) == 1:
        root = resolved[0]
        if root.is_file():
            return analyzed_path, {root.name: _read_input_text(root)}
        return analyzed_path, {
            file.relative_to(root).as_posix(): _read_input_text(file) for file in _iter_input_files(root)
        }
    common = Path(os.path.commonpath([str(path) for path in resolved]))
    if common.is_file():
        common = common.parent
    sources: dict[str, str] = {}
    for root in resolved:
        for file in _iter_input_files(root):
            relative = file.relative_to(common).as_posix()
            if relative in sources:
                raise AnalysisError(f"duplicate input path: {relative}")
            sources[relative] = _read_input_text(file)
    return analyzed_path, sources


def _sources_digest(reader: _SourceReader, inventory: list[SourceFile]) -> str:
    digest = hashlib.sha256()
    for item in inventory:
        digest.update(item.path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(reader.read_text(item.path).encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def _canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _sort_json_value(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _sort_json_value(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [_sort_json_value(item) for item in value]
    return value
