"""Generic observation contracts, memory values, and staged controller cycle."""

from .activation import (
    MEMORY_ACTIVATION_SCHEMA,
    ActivatedMemoryStage,
    MemoryActivation,
    instantiate_memory_implementation,
    load_memory_implementation,
    load_memory_stage_if_present,
    read_memory_activation,
)
from .cycle import (
    DECISION_CYCLE_RESULT_SCHEMA,
    DecisionCycle,
    DecisionCycleResult,
    DecisionFrameContext,
    DecisionStages,
)
from .memory import (
    DEFAULT_MAX_DIAGNOSTIC_CHARS,
    DEFAULT_MAX_PROPERTY_BYTES,
    DEFAULT_MAX_SERIALIZED_BYTES,
    MEMORY_HEALTH_VALUES,
    MEMORY_SNAPSHOT_SCHEMA,
    MIN_MAX_SERIALIZED_BYTES,
    MemoryBounds,
    MemoryProvenance,
    MemorySnapshot,
    RetainedEvidence,
    canonical_json_bytes,
    canonical_json_utf8,
    detach_memory_snapshot,
    empty_memory_snapshot,
    ensure_strict_json_value,
    error_memory_snapshot,
    serialized_mapping_bytes,
    serialized_memory_snapshot_bytes,
    unavailable_memory_snapshot,
)
from .observation import OBSERVATION_SCHEMA, Observation, observation_from_perception
from .plugin import MemoryImplementation
from .shadow_ids import ShadowCycleInputError
from .decision_data import (
    DECISION_DATA_SOURCE_SCHEMA,
    ComponentEnvelope,
    DecisionDataSource,
    build_decision_data_source,
)
from .action_proposal import (
    ACTION_PROPOSAL_SCHEMA,
    ActionProposal,
    ProposedVehicleCommand,
    SourceRef,
)
from .action_plan import ACTION_PLAN_SCHEMA, ActionPlan, SELECTOR_ID, select_action_plan
from .shadow_authority import (
    SHADOW_AUTHORITY_RESULT_SCHEMA,
    SHADOW_DECISION_CYCLE_RESULT_SCHEMA,
    ShadowAuthorityResult,
    ShadowDecisionCycleResult,
)
from .shadow_runner import ENGINE_ID, ShadowProposalsConfig, ShadowProposalsEngine

__all__ = [
    "DECISION_CYCLE_RESULT_SCHEMA",
    "DEFAULT_MAX_DIAGNOSTIC_CHARS",
    "DEFAULT_MAX_PROPERTY_BYTES",
    "DEFAULT_MAX_SERIALIZED_BYTES",
    "MEMORY_ACTIVATION_SCHEMA",
    "MEMORY_HEALTH_VALUES",
    "MEMORY_SNAPSHOT_SCHEMA",
    "MIN_MAX_SERIALIZED_BYTES",
    "OBSERVATION_SCHEMA",
    "ActivatedMemoryStage",
    "DecisionCycle",
    "DecisionCycleResult",
    "DecisionFrameContext",
    "DecisionStages",
    "MemoryActivation",
    "MemoryBounds",
    "MemoryImplementation",
    "MemoryProvenance",
    "MemorySnapshot",
    "Observation",
    "RetainedEvidence",
    "canonical_json_bytes",
    "canonical_json_utf8",
    "detach_memory_snapshot",
    "empty_memory_snapshot",
    "ensure_strict_json_value",
    "error_memory_snapshot",
    "instantiate_memory_implementation",
    "load_memory_implementation",
    "load_memory_stage_if_present",
    "observation_from_perception",
    "read_memory_activation",
    "serialized_mapping_bytes",
    "serialized_memory_snapshot_bytes",
    "unavailable_memory_snapshot",
    "ShadowCycleInputError",
    "DECISION_DATA_SOURCE_SCHEMA",
    "ComponentEnvelope",
    "DecisionDataSource",
    "build_decision_data_source",
    "ACTION_PROPOSAL_SCHEMA",
    "ActionProposal",
    "ProposedVehicleCommand",
    "SourceRef",
    "ACTION_PLAN_SCHEMA",
    "ActionPlan",
    "SELECTOR_ID",
    "select_action_plan",
    "SHADOW_AUTHORITY_RESULT_SCHEMA",
    "SHADOW_DECISION_CYCLE_RESULT_SCHEMA",
    "ShadowAuthorityResult",
    "ShadowDecisionCycleResult",
    "ENGINE_ID",
    "ShadowProposalsConfig",
    "ShadowProposalsEngine",
]
