from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
CONTRACT_SOURCE = DOCS / "milestones" / "README.md"
CONTRACT_RENDER = DOCS / "milestones" / "planning-contract.html"


class MilestonePlanningTests(unittest.TestCase):
    def test_rendered_contract_identifies_current_markdown_source(self) -> None:
        source = CONTRACT_SOURCE.read_text(encoding="utf-8")
        rendered = CONTRACT_RENDER.read_text(encoding="utf-8")
        expected_digest = hashlib.sha256(source.encode("utf-8")).hexdigest()

        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )

        self.assertIsNotNone(match)
        self.assertEqual(match.group(1), expected_digest)
        self.assertIn("Generated by docs/render_markdown.py", rendered)

    def test_active_milestone_embeds_the_shared_contract(self) -> None:
        guide = (DOCS / "README.md").read_text(encoding="utf-8")
        match = re.search(
            r"Milestone \d+,\s*\[[^]]+\]\((milestones/[^)]+/plan\.html)\),\s*is active",
            guide,
        )
        self.assertIsNotNone(match, "docs/README.md must identify one active milestone plan")

        active_plan = DOCS / match.group(1)
        plan_html = active_plan.read_text(encoding="utf-8")
        self.assertIn("data-shared-planning-contract", plan_html)
        self.assertIn('src="../planning-contract.html"', plan_html)


if __name__ == "__main__":
    unittest.main(verbosity=2)
