from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
MILESTONES = DOCS / "milestones"
CONTRACT_SOURCE = MILESTONES / "README.md"
CONTRACT_RENDER = MILESTONES / "planning-contract.html"
GUIDE = DOCS / "README.md"
PR_TEMPLATE = ROOT / ".github" / "pull_request_template.md"
MILESTONE_PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "milestone.md"


def _active_plan_paths() -> tuple[Path, Path]:
    guide = GUIDE.read_text(encoding="utf-8")
    match = re.search(
        r"milestones/(\d+-[^)\s]+)/plan\.html",
        guide,
    )
    if not match:
        raise AssertionError("docs/README.md must link an active milestone plan.html")
    slug = match.group(1)
    plan_md = MILESTONES / slug / "plan.md"
    plan_html = MILESTONES / slug / "plan.html"
    return plan_md, plan_html


class MilestonePlanningTests(unittest.TestCase):
    def test_rendered_contract_identifies_current_markdown_source(self) -> None:
        source = CONTRACT_SOURCE.read_text(encoding="utf-8")
        rendered = CONTRACT_RENDER.read_text(encoding="utf-8")
        expected_digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected_digest)
        self.assertIn("Generated by docs/render_markdown.py", rendered)

    def test_active_plan_markdown_is_canonical_and_html_is_generated(self) -> None:
        plan_md, plan_html = _active_plan_paths()
        self.assertTrue(plan_md.is_file(), f"missing canonical plan: {plan_md}")
        self.assertTrue(plan_html.is_file(), f"missing generated plan: {plan_html}")
        source = plan_md.read_text(encoding="utf-8")
        rendered = plan_html.read_text(encoding="utf-8")
        expected = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected)
        self.assertIn("Generated by docs/render_markdown.py", rendered)
        self.assertIn("Canonical source:", rendered)

    def test_active_plan_has_required_compact_sections(self) -> None:
        plan_md, _ = _active_plan_paths()
        text = plan_md.read_text(encoding="utf-8")
        for heading in (
            "## Objective",
            "## Completion Usage",
            "## Scope Boundaries",
            "## Exit Criteria",
            "## Current Delivery",
            "### Current Frontier",
            "### Next-Frontier Candidate",
            "## Accepted Review Units",
            "## Open Risks And Unverified Assumptions",
            "## Milestone Decisions",
            "## Closeout",
        ):
            self.assertIn(heading, text, f"missing section {heading}")

    def test_active_plan_has_one_current_frontier_and_at_most_one_next(self) -> None:
        plan_md, _ = _active_plan_paths()
        text = plan_md.read_text(encoding="utf-8")
        self.assertEqual(text.count("### Current Frontier"), 1)
        self.assertEqual(text.count("### Next-Frontier Candidate"), 1)
        self.assertIn("Review question:", text)
        self.assertRegex(text, r"Milestone branch\s*\|\s*`milestone/")

    def test_active_plan_exit_criteria_use_stable_ids(self) -> None:
        plan_md, _ = _active_plan_paths()
        text = plan_md.read_text(encoding="utf-8")
        ids = re.findall(r"\|\s*(M\d{3}-\d{2})\s*\|", text)
        self.assertGreaterEqual(len(ids), 3)
        self.assertEqual(len(ids), len(set(ids)), "exit criteria IDs must be unique")
        for status in ("Met", "Partial", "Blocked", "Unmet"):
            if status in text:
                break
        else:
            self.fail("exit criteria table should use allowed statuses")

    def test_docs_guide_is_navigation_only_for_progress(self) -> None:
        guide = GUIDE.read_text(encoding="utf-8")
        self.assertIn("Active Milestone", guide)
        # Must not restate detailed package progress or remaining-for-closeout.
        lowered = guide.lower()
        for banned in (
            "remaining for closeout",
            "package 5a",
            "package 5b",
            "required remediation order",
        ):
            self.assertNotIn(banned, lowered)

    def test_review_unit_pr_template_has_required_headings(self) -> None:
        self.assertTrue(PR_TEMPLATE.is_file())
        text = PR_TEMPLATE.read_text(encoding="utf-8")
        for heading in (
            "## Milestone Context",
            "## Review Kind",
            "## Review Question",
            "## Invariant Or Acceptance Contract",
            "## Adversarial Matrix",
            "## Scope",
            "## File Impact",
            "## Validation",
        ):
            self.assertIn(heading, text)

    def test_cumulative_milestone_pr_template_targets_main_topology(self) -> None:
        self.assertTrue(MILESTONE_PR_TEMPLATE.is_file())
        text = MILESTONE_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("Targets: `main`", text)
        self.assertIn("milestone branch", text.lower())
        self.assertIn("## Accepted Review Units", text)

    def test_contract_defines_work_unit_terms_and_branch_model(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        for term in (
            "### Milestone",
            "### Frontier",
            "### Review Unit",
            "### Task",
            "### Evidence Unit",
            "### Repair Cycle",
            "### Closeout",
            "milestone/<number>-<slug>",
            "m<number>/<review-unit>-<slug>",
        ):
            self.assertIn(term, text)
        self.assertIn("targets the milestone branch", text.lower())

    def test_contract_discourages_multiple_independent_review_questions(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        self.assertIn("Singular Review Question Rule", text)
        self.assertIn('requires “and”', text)


if __name__ == "__main__":
    unittest.main(verbosity=2)
