from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path

from docs.milestones.workflow import (
    parse_table,
    validate_plan_path,
    validate_repair_cycle_governance_body,
)


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
MILESTONES = DOCS / "milestones"
CONTRACT_SOURCE = MILESTONES / "README.md"
CONTRACT_RENDER = MILESTONES / "planning-contract.html"
GUIDE = DOCS / "README.md"
PR_TEMPLATE = ROOT / ".github" / "pull_request_template.md"
PROPOSAL_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "proposal.md"
)
PROPOSAL_GUIDANCE = DOCS / "guidance" / "proposal-vs-implementation.md"
PROPOSAL_AMENDMENT_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "proposal-amendment.md"
)
IMPLEMENTATION_ADJUNCT_PR_TEMPLATE = (
    ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "implementation-adjunct.md"
)
MILESTONE_PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "milestone.md"
REPAIR_PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE" / "repair.md"
TEST_WORKFLOW = ROOT / ".github" / "workflows" / "tests.yml"


def _active_milestone_section() -> str:
    guide = GUIDE.read_text(encoding="utf-8")
    match = re.search(
        r"^## Active Milestone\s*\n(?P<body>.*?)(?=^## |\Z)",
        guide,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise AssertionError("docs/README.md must contain an Active Milestone section")
    return match.group("body")


def _active_plan_paths() -> tuple[Path, Path] | None:
    section = _active_milestone_section()
    if re.search(r"^\*\*None\.\*\*", section, re.MULTILINE):
        return None
    match = re.search(
        r"milestones/(\d+-[^)\s]+)/plan\.html",
        section,
    )
    if not match:
        raise AssertionError("docs/README.md must link an active milestone plan.html")
    slug = match.group(1)
    plan_md = MILESTONES / slug / "plan.md"
    plan_html = MILESTONES / slug / "plan.html"
    return plan_md, plan_html


class MilestonePlanningTests(unittest.TestCase):
    def test_rendered_contract_identifies_current_markdown_source(self) -> None:
        source = CONTRACT_SOURCE.read_text(encoding="utf-8")
        rendered = CONTRACT_RENDER.read_text(encoding="utf-8")
        expected_digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected_digest)
        self.assertIn("Generated by docs/render_markdown.py", rendered)

    def test_active_plan_markdown_is_canonical_and_html_is_generated(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, plan_html = paths
        self.assertTrue(plan_md.is_file(), f"missing canonical plan: {plan_md}")
        self.assertTrue(plan_html.is_file(), f"missing generated plan: {plan_html}")
        source = plan_md.read_text(encoding="utf-8")
        rendered = plan_html.read_text(encoding="utf-8")
        expected = hashlib.sha256(source.encode("utf-8")).hexdigest()
        match = re.search(
            r'<meta name="source-sha256" content="([a-f0-9]{64})">',
            rendered,
        )
        self.assertIsNotNone(match)
        assert match is not None
        self.assertEqual(match.group(1), expected)
        self.assertIn("Generated by docs/render_markdown.py", rendered)
        self.assertIn("Canonical source:", rendered)

    def test_active_plan_has_required_compact_sections(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        text = plan_md.read_text(encoding="utf-8")
        for heading in (
            "## Objective",
            "## Completion Usage",
            "## Scope Boundaries",
            "## Exit Criteria",
            "## Current Delivery",
            "### Current Frontier",
            "### Next-Frontier Candidate",
            "## Workflow History",
            "## Accepted Review Units",
            "## Open Risks And Unverified Assumptions",
            "## Milestone Decisions",
            "## Closeout",
        ):
            self.assertIn(heading, text, f"missing section {heading}")

    def test_completion_usage_starts_with_primary_demonstration(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        table = parse_table(
            plan_md.read_text(encoding="utf-8"),
            "## Completion Usage",
        )
        self.assertEqual(
            table.header,
            ("Workflow", "Starting state", "Execution", "Success signal", "Criteria"),
        )
        self.assertTrue(table.rows, "Completion Usage must contain workflows")
        self.assertEqual(table.rows[0][0], "Primary demonstration")

    def test_active_plan_has_one_current_frontier_and_at_most_one_next(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        self.assertFalse(state.current.is_empty)
        # Terminal closeout may leave next empty; otherwise at most one named next.
        if not state.next_frontier.is_empty:
            self.assertTrue(state.next_frontier.fields["review question"])
        self.assertTrue(state.current.fields["review question"])
        self.assertTrue(state.milestone_branch.startswith("milestone/"))

    def test_active_plan_exit_criteria_use_stable_ids(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        ids = [row[0] for row in state.criteria.rows]
        self.assertGreaterEqual(len(ids), 3)
        self.assertEqual(len(ids), len(set(ids)), "exit criteria IDs must be unique")

    def test_docs_guide_is_navigation_only_for_progress(self) -> None:
        guide = GUIDE.read_text(encoding="utf-8")
        self.assertIn("Active Milestone", guide)
        # Must not restate detailed package progress or remaining-for-closeout.
        lowered = guide.lower()
        for banned in (
            "remaining for closeout",
            "package 5a",
            "package 5b",
            "required remediation order",
        ):
            self.assertNotIn(banned, lowered)

    def test_docs_guide_identifies_an_active_milestone_or_explicit_none(self) -> None:
        section = _active_milestone_section()
        paths = _active_plan_paths()
        if paths is None:
            self.assertRegex(section, r"^\s*\*\*None\.\*\*")
            return
        plan_md, plan_html = paths
        self.assertNotIn("**None.**", section)
        self.assertTrue(plan_md.is_file())
        self.assertTrue(plan_html.is_file())

    def test_review_unit_pr_template_has_required_headings(self) -> None:
        self.assertTrue(PR_TEMPLATE.is_file())
        text = PR_TEMPLATE.read_text(encoding="utf-8")
        for heading in (
            "## Milestone Context",
            "## Accepted Proposal",
            "## Review Kind",
            "## Review Question",
            "## Repair Cycle Ledger",
            "## Validation",
        ):
            self.assertIn(heading, text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)
        self.assertIn("matching the canonical milestone plan", text)

    def test_proposal_pr_template_forbids_implementation(self) -> None:
        self.assertTrue(PROPOSAL_PR_TEMPLATE.is_file())
        text = PROPOSAL_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Independence Check", text)
        self.assertIn("## Review Kind", text)
        self.assertIn("## Operator Want", text)
        self.assertIn("Trust And Authority Model", text)
        self.assertIn("Evidence Topology And Capture Strategy", text)
        self.assertIn("No product or runtime implementation changed", text)
        self.assertIn("Proposal artifact", text)
        self.assertIn("## Contract Review Receipt", text)
        self.assertIn("current repository push authority", text)
        self.assertIn("unedited COMMENT review", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_universal_claim_contractability_is_visible_in_author_guidance(
        self,
    ) -> None:
        contract = CONTRACT_SOURCE.read_text(encoding="utf-8")
        guidance = PROPOSAL_GUIDANCE.read_text(encoding="utf-8")
        for phrase in (
            "Trust And Authority Model",
            "Evidence Topology And Capture Strategy",
        ):
            self.assertIn(phrase, contract)
            self.assertIn(phrase, guidance)
        normalized_contract = " ".join(contract.split())
        self.assertIn(
            "consistency, provenance, and authenticity",
            normalized_contract,
        )
        self.assertIn("canonical capture is ready", guidance)

    def test_proposal_amendment_template_preserves_accepted_contract(self) -> None:
        self.assertTrue(PROPOSAL_AMENDMENT_PR_TEMPLATE.is_file())
        text = PROPOSAL_AMENDMENT_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Review Kind", text)
        self.assertIn("## Evidence Requiring Amendment", text)
        self.assertIn("## Operator Want", text)
        self.assertIn("Trust And Authority Model", text)
        self.assertIn("Evidence Topology And Capture Strategy", text)
        self.assertIn("No accepted proposal or prior amendment was modified", text)
        self.assertIn("No product or runtime implementation changed", text)
        self.assertIn("## Contract Review Receipt", text)
        self.assertIn("current repository push authority", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_implementation_adjunct_template_records_human_compatibility(self) -> None:
        self.assertTrue(IMPLEMENTATION_ADJUNCT_PR_TEMPLATE.is_file())
        text = IMPLEMENTATION_ADJUNCT_PR_TEMPLATE.read_text(encoding="utf-8")
        for heading in (
            "## Parent Implementation",
            "## Operator Request",
            "## HITL Authorization",
            "## Review Question",
            "## Compatibility",
            "## Evidence Impact",
            "## Repair Cycle Ledger",
            "## Validation",
        ):
            self.assertIn(heading, text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertIn("Requested disposition: `implement-now`", text)
        self.assertIn("parent contract remains true without this adjunct", text)
        self.assertIn("Base implementation branch", text)

    def test_cumulative_milestone_pr_template_targets_main_topology(self) -> None:
        self.assertTrue(MILESTONE_PR_TEMPLATE.is_file())
        text = MILESTONE_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("Targets: `main`", text)
        self.assertIn("milestone branch", text.lower())
        self.assertIn("## Accepted Review Units", text)
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_repair_template_carries_cycle_and_escalation_receipts(self) -> None:
        self.assertTrue(REPAIR_PR_TEMPLATE.is_file())
        text = REPAIR_PR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("## Review Repair Summary", CONTRACT_SOURCE.read_text(encoding="utf-8"))
        self.assertIn("## Repair Cycle Ledger", text)
        self.assertNotIn("## Repair Escalation", text)
        self.assertNotIn("## Repair Continuation Audit", text)

    def test_review_unit_template_repair_receipt_defaults_are_valid(self) -> None:
        for path in (
            PR_TEMPLATE,
            PROPOSAL_PR_TEMPLATE,
            PROPOSAL_AMENDMENT_PR_TEMPLATE,
            IMPLEMENTATION_ADJUNCT_PR_TEMPLATE,
            MILESTONE_PR_TEMPLATE,
            REPAIR_PR_TEMPLATE,
        ):
            with self.subTest(path=path):
                self.assertEqual(
                    validate_repair_cycle_governance_body(
                        path.read_text(encoding="utf-8")
                    ),
                    0,
                )

    def test_pr_body_edits_revalidate_repair_receipts(self) -> None:
        text = TEST_WORKFLOW.read_text(encoding="utf-8")
        self.assertRegex(text, r"types:.*\bedited\b")
        self.assertIn("pull-requests: read", text)
        self.assertIn("GH_TOKEN:", text)

    def test_pr_body_edits_rerun_review_kind_validation(self) -> None:
        text = TEST_WORKFLOW.read_text(encoding="utf-8")
        self.assertRegex(
            text,
            r"pull_request:\s*\n\s+types: \[[^\]]*edited[^\]]*\]",
        )

    def test_contract_defines_work_unit_terms_and_branch_model(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        for term in (
            "### Milestone",
            "### Frontier",
            "### Review Unit",
            "### Task",
            "### Evidence Unit",
            "### Repair Cycle",
            "### Closeout",
            "milestone/<number>-<slug>",
            "m<number>/<frontier>-proposal",
            "m<number>/<frontier>--adjunct-<slug>",
        ):
            self.assertIn(term, text)
        self.assertIn("targets the milestone branch", text.lower())

    def test_contract_routes_human_discovery_without_reopening_parent(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("### Human Discovery During Implementation", text)
        self.assertIn("parent contract remains true", text.lower())
        self.assertIn("implement-now", text)
        self.assertIn("creates no plan transition", normalized)
        self.assertIn("review the integrated parent in totality", normalized)

    def test_contract_discourages_multiple_independent_review_questions(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        self.assertIn("Singular Review Question Rule", text)
        self.assertIn('requires “and”', text)

    def test_contract_has_evidence_based_repair_continuation_gate(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("There is no cycle count that pauses review", text)
        self.assertIn("Closed implementation review", text)
        self.assertIn("a new PR number is not reviewability evidence", normalized)
        self.assertIn("currently fails closed", normalized)
        self.assertIn("becomes authoritative only after", normalized)
        self.assertIn("already open at merge do not migrate automatically", normalized)
        self.assertIn("introducing PR remains governed by its base contract", normalized)
        self.assertIn("Repair Cycle Ledger", text)
        self.assertNotIn("Repair Escalation", text)

    def test_contract_assigns_frontier_handoff_to_executable_workflow(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("Frontier handoff:", text)
        self.assertIn("docs/milestones/workflow.py complete-implementation", text)
        self.assertIn("handoff --receipt <path>", text)
        self.assertIn("docs/milestones/workflow.py start-proposal", text)
        self.assertIn("docs/milestones/workflow.py accept-proposal", text)
        self.assertIn(
            "docs/milestones/workflow.py start-proposal-amendment",
            text,
        )
        self.assertIn(
            "docs/milestones/workflow.py accept-proposal-amendment",
            text,
        )
        self.assertIn("docs/milestones/workflow.py start-implementation", text)
        self.assertIn("merge commit that is not already an ancestor", normalized)
        self.assertIn("promotes the reviewed next candidate", normalized)

    def test_contract_requires_next_frontier_minimal_acceptance_contract(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        normalized = " ".join(text.split())
        self.assertIn("pre-implementation acceptance contract", text)
        self.assertIn("frozen before the proposal branch opens", normalized)
        self.assertIn("enforcement or acceptance owner", text)
        self.assertIn("A name plus a vague “likely question” alone is not a candidate", text)
        self.assertIn("empty next-frontier slot", text)

    def test_contract_requires_one_primary_completion_demonstration(self) -> None:
        text = CONTRACT_SOURCE.read_text(encoding="utf-8")
        self.assertIn("The first body row must be `Primary demonstration`", text)
        self.assertIn("leave schemas, lifecycle matrices, edge cases", text)

    def test_active_plan_next_frontier_records_minimal_contract_fields(self) -> None:
        paths = _active_plan_paths()
        if paths is None:
            return
        plan_md, _ = paths
        state = validate_plan_path(plan_md)
        frontiers = [state.current]
        if not state.next_frontier.is_empty:
            frontiers.append(state.next_frontier)
        for frontier in frontiers:
            for field in (
                "proposal branch",
                "implementation branch",
                "proposal path",
                "review kind",
                "review question",
                "acceptance owner",
                "exit criteria affected",
                "prerequisite",
                "non-goals",
            ):
                self.assertTrue(frontier.fields[field], f"missing frontier field {field}")
        # Active frontier may be anywhere in the proposal/implementation machine.
        from docs.milestones.workflow import WORKFLOW_STATES

        self.assertIn(
            state.current.fields["workflow state"],
            WORKFLOW_STATES,
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
