"""Baseline paths for the decision-cycle module move.

Legacy columns stay when an owner moves. Update the canonical module and
attribute so the old spec, export, or import still resolves to that owner.
Do not rebuild this list from the current tree: dropping a string from a
catalog or ``__all__`` does not retire the path.

Specs include production ``module:attribute`` paths and the tracked perception
manifests: entrypoints, the camera provider, and memory implementation specs.
Exports include ``__all__`` names plus lab and workbench imports that are not
on those lists.
"""

from __future__ import annotations

# (legacy spec, canonical module, canonical attribute)
LEGACY_SPECS: tuple[tuple[str, str, str], ...] = (
    ("autonomy.perception.plugin_runner:PluginPerceptionMapper", "autonomy.decision_cycle.perception.plugin_runner", "PluginPerceptionMapper"),
    ("autonomy.runtime.engine:IdleAutonomyEngine", "autonomy.runtime.engine", "IdleAutonomyEngine"),
    ("cli.automa_cli.lab_plugins:LabPerceptionMapper", "cli.automa_cli.lab_plugins", "LabPerceptionMapper"),
    ("implementations.decision.live_adapter:ObstacleAvoidanceAutonomyEngine", "implementations.runtime.engines.mode_gated_action", "ObstacleAvoidanceAutonomyEngine"),
    ("implementations.decision.shadow_adapter:ShadowProposalsAutonomyEngine", "implementations.runtime.engines.hold_action", "ShadowProposalsAutonomyEngine"),
    ("implementations.memory.bounded_evidence:BoundedEvidenceLedger", "implementations.decision_cycle.memory.bounded_evidence.plugin", "BoundedEvidenceLedger"),
    ("implementations.perception.components.camera:provide_camera_frame", "implementations.decision_cycle.perception.components.camera", "provide_camera_frame"),
    ("implementations.perception.motion.tracks:MotionTracksPlugin", "implementations.decision_cycle.perception.motion_tracks.plugin", "MotionTracksPlugin"),
    ("implementations.perception.observation.plugin:FrameObservationPlugin", "implementations.decision_cycle.perception.frame_observation.plugin", "FrameObservationPlugin"),
    ("implementations.perception.obstruction_tracks:MultiObstructionTracksPlugin", "implementations.decision_cycle.perception.obstruction_tracks.plugin", "MultiObstructionTracksPlugin"),
    ("implementations.perception.preparation.vlm:VlmPrepPlugin", "implementations.decision_cycle.perception.vlm_preparation.plugin", "VlmPrepPlugin"),
    ("implementations.perception.simulation.color_targets:SimColorTargetsPlugin", "implementations.decision_cycle.perception.sim_color_targets.plugin", "SimColorTargetsPlugin"),
    ("implementations.perception.traversability.plugin:FloorPlanePlugin", "implementations.decision_cycle.perception.floor_plane.plugin", "FloorPlanePlugin"),
    # Perception manifest entrypoints and the memory implementation spec.
    # The camera provider is the production spec above.
    ("lab.plugins.memory.multi_obstruction_tracks.plugin:MultiObstructionMemory", "lab.plugins.memory.multi_obstruction_tracks.plugin", "MultiObstructionMemory"),
    ("lab.plugins.perception.classical_regions.src.plugin:ClassicalRegionPlugin", "lab.plugins.perception.classical_regions.src.plugin", "ClassicalRegionPlugin"),
    ("lab.plugins.perception.composite_box_fusion.src.plugin:CompositeBoxFusionPlugin", "lab.plugins.perception.composite_box_fusion.src.plugin", "CompositeBoxFusionPlugin"),
    ("lab.plugins.perception.composite_box_fusion_object_separated.src.plugin:CompositeBoxFusionPlugin", "lab.plugins.perception.composite_box_fusion_object_separated.src.plugin", "CompositeBoxFusionPlugin"),
    ("lab.plugins.perception.fastsam.src.plugin:FastSamRegionPlugin", "lab.plugins.perception.fastsam.src.plugin", "FastSamRegionPlugin"),
    ("lab.plugins.perception.floor_continuity.src.plugin:FloorContinuityPlugin", "lab.plugins.perception.floor_continuity.src.plugin", "FloorContinuityPlugin"),
    ("lab.plugins.perception.floor_continuity_capture.src.plugin:CaptureFloorContinuityPlugin", "lab.plugins.perception.floor_continuity_capture.src.plugin", "CaptureFloorContinuityPlugin"),
    ("lab.plugins.perception.floor_continuity_temporal.src.plugin:TemporalFloorContinuityPlugin", "lab.plugins.perception.floor_continuity_temporal.src.plugin", "TemporalFloorContinuityPlugin"),
    ("lab.plugins.perception.multi_obstruction_tracks.src.plugin:MultiObstructionTracksPlugin", "lab.plugins.perception.multi_obstruction_tracks.src.plugin", "MultiObstructionTracksPlugin"),
)

# (legacy module, canonical module). Both stay importable. They are not
# required to be the same module object once a forwarding shim exists.
LEGACY_MODULES: tuple[tuple[str, str], ...] = (
    # Engine spec modules are the same module object as their owner, so a
    # manager reload through the legacy spec reloads the engine code.
    ("implementations.decision.live_adapter", "implementations.runtime.engines.mode_gated_action"),
    ("implementations.decision.shadow_adapter", "implementations.runtime.engines.hold_action"),
    ("lab.plugins.perception.worker", "lab.plugins.perception.worker"),
)

# (legacy module, legacy attribute, canonical module, canonical attribute)
LEGACY_EXPORTS: tuple[tuple[str, str, str, str], ...] = (
    # autonomy.decision
    ("autonomy.decision", "ACTION_PLAN_SCHEMA", "autonomy.decision_cycle.planning.values", "ACTION_PLAN_SCHEMA"),
    ("autonomy.decision", "ACTION_PROPOSAL_SCHEMA", "autonomy.decision_cycle.proposal.values", "ACTION_PROPOSAL_SCHEMA"),
    ("autonomy.decision", "ActionPlan", "autonomy.decision_cycle.planning.values", "ActionPlan"),
    ("autonomy.decision", "ActionProposal", "autonomy.decision_cycle.proposal.values", "ActionProposal"),
    ("autonomy.decision", "ActivatedMemoryStep", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.decision", "ComponentEnvelope", "autonomy.decision_cycle.proposal.inputs", "ComponentEnvelope"),
    ("autonomy.decision", "DECISION_CYCLE_RESULT_SCHEMA", "autonomy.decision.cycle", "DECISION_CYCLE_RESULT_SCHEMA"),
    ("autonomy.decision", "DECISION_DATA_SOURCE_SCHEMA", "autonomy.decision_cycle.proposal.inputs", "DECISION_DATA_SOURCE_SCHEMA"),
    ("autonomy.decision", "DEFAULT_MAX_DIAGNOSTIC_CHARS", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_DIAGNOSTIC_CHARS"),
    ("autonomy.decision", "DEFAULT_MAX_PROPERTY_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_PROPERTY_BYTES"),
    ("autonomy.decision", "DEFAULT_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_SERIALIZED_BYTES"),
    ("autonomy.decision", "DecisionCycle", "autonomy.decision.cycle", "DecisionCycle"),
    ("autonomy.decision", "DecisionCycleResult", "autonomy.decision.cycle", "DecisionCycleResult"),
    ("autonomy.decision", "DecisionDataSource", "autonomy.decision_cycle.proposal.inputs", "DecisionDataSource"),
    ("autonomy.decision", "DecisionFrameContext", "autonomy.decision_cycle.context", "DecisionFrameContext"),
    ("autonomy.decision", "DecisionSteps", "autonomy.decision.cycle", "DecisionSteps"),
    ("autonomy.decision", "ENGINE_ID", "autonomy.decision_cycle.action", "ENGINE_ID"),
    ("autonomy.decision", "MEMORY_ACTIVATION_SCHEMA", "autonomy.decision_cycle.memory.activation", "MEMORY_ACTIVATION_SCHEMA"),
    ("autonomy.decision", "MEMORY_HEALTH_VALUES", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_HEALTH_VALUES"),
    ("autonomy.decision", "MEMORY_SNAPSHOT_SCHEMA", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_SNAPSHOT_SCHEMA"),
    ("autonomy.decision", "MIN_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "MIN_MAX_SERIALIZED_BYTES"),
    ("autonomy.decision", "MemoryActivation", "autonomy.decision_cycle.memory.activation", "MemoryActivation"),
    ("autonomy.decision", "MemoryBounds", "autonomy.decision_cycle.memory.snapshots.values", "MemoryBounds"),
    ("autonomy.decision", "MemoryImplementation", "autonomy.decision_cycle.memory.plugin", "MemoryImplementation"),
    ("autonomy.decision", "MemoryProvenance", "autonomy.decision_cycle.memory.snapshots.values", "MemoryProvenance"),
    ("autonomy.decision", "MemorySnapshot", "autonomy.decision_cycle.memory.snapshots.values", "MemorySnapshot"),
    ("autonomy.decision", "MemoryUpdateError", "autonomy.decision_cycle.memory.errors", "MemoryUpdateError"),
    ("autonomy.decision", "OBSERVATION_SCHEMA", "autonomy.decision_cycle.observation.values", "OBSERVATION_SCHEMA"),
    ("autonomy.decision", "Observation", "autonomy.decision_cycle.observation.values", "Observation"),
    ("autonomy.decision", "ProposedVehicleCommand", "autonomy.decision_cycle.proposal.values", "ProposedVehicleCommand"),
    ("autonomy.decision", "RetainedEvidence", "autonomy.decision_cycle.memory.snapshots.values", "RetainedEvidence"),
    ("autonomy.decision", "SELECTOR_ID", "autonomy.decision_cycle.planning.values", "SELECTOR_ID"),
    ("autonomy.decision", "SHADOW_AUTHORITY_RESULT_SCHEMA", "autonomy.decision_cycle.action_gate.hold", "SHADOW_AUTHORITY_RESULT_SCHEMA"),
    ("autonomy.decision", "SHADOW_DECISION_CYCLE_RESULT_SCHEMA", "autonomy.decision_cycle.result", "SHADOW_DECISION_CYCLE_RESULT_SCHEMA"),
    ("autonomy.decision", "ShadowAuthorityResult", "autonomy.decision_cycle.action_gate.hold", "ShadowAuthorityResult"),
    ("autonomy.decision", "ShadowCycleInputError", "autonomy.decision_cycle.action_identifiers", "ShadowCycleInputError"),
    ("autonomy.decision", "ShadowDecisionCycleResult", "autonomy.decision_cycle.result", "ShadowDecisionCycleResult"),
    ("autonomy.decision", "ShadowProposalsConfig", "autonomy.decision_cycle.action", "ShadowProposalsConfig"),
    ("autonomy.decision", "ShadowProposalsEngine", "autonomy.decision_cycle.action", "ShadowProposalsEngine"),
    ("autonomy.decision", "SourceRef", "autonomy.decision_cycle.proposal.values", "SourceRef"),
    ("autonomy.decision", "build_decision_data_source", "autonomy.decision_cycle.proposal.inputs", "build_decision_data_source"),
    ("autonomy.decision", "canonical_json_bytes", "autonomy.serialization", "canonical_json_size_bytes"),
    ("autonomy.decision", "canonical_json_utf8", "autonomy.serialization", "canonical_json_utf8"),
    ("autonomy.decision", "detach_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "detach_memory_snapshot"),
    ("autonomy.decision", "empty_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "empty_memory_snapshot"),
    ("autonomy.decision", "ensure_strict_json_value", "autonomy.serialization", "ensure_strict_json_value"),
    ("autonomy.decision", "error_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "error_memory_snapshot"),
    ("autonomy.decision", "instantiate_memory_implementation", "autonomy.decision_cycle.memory.activation", "instantiate_memory_implementation"),
    ("autonomy.decision", "load_memory_implementation", "autonomy.decision_cycle.memory.activation", "load_memory_implementation"),
    ("autonomy.decision", "load_memory_step_if_present", "autonomy.decision_cycle.memory.activation", "load_memory_step_if_present"),
    ("autonomy.decision", "observation_from_perception", "autonomy.decision_cycle.observation.step", "observation_from_perception"),
    ("autonomy.decision", "read_memory_activation", "autonomy.decision_cycle.memory.activation", "read_memory_activation"),
    ("autonomy.decision", "select_action_plan", "autonomy.decision_cycle.planning.selector", "select_action_plan"),
    ("autonomy.decision", "serialized_mapping_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_mapping_bytes"),
    ("autonomy.decision", "serialized_memory_snapshot_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_memory_snapshot_bytes"),
    ("autonomy.decision", "unavailable_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "unavailable_memory_snapshot"),
    ("autonomy.decision.action_plan", "ACTION_PLAN_SCHEMA", "autonomy.decision_cycle.planning.values", "ACTION_PLAN_SCHEMA"),
    ("autonomy.decision.action_plan", "ActionPlan", "autonomy.decision_cycle.planning.values", "ActionPlan"),
    ("autonomy.decision.action_plan", "MAX_CANDIDATES", "autonomy.decision_cycle.planning.values", "MAX_CANDIDATES"),
    ("autonomy.decision.action_plan", "MAX_PLAN_BYTES", "autonomy.decision_cycle.planning.values", "MAX_PLAN_BYTES"),
    ("autonomy.decision.action_plan", "MAX_PLAN_METADATA_BYTES", "autonomy.decision_cycle.planning.values", "MAX_PLAN_METADATA_BYTES"),
    ("autonomy.decision.action_plan", "PlanContribution", "autonomy.decision_cycle.planning.values", "PlanContribution"),
    ("autonomy.decision.action_plan", "SELECTOR_ID", "autonomy.decision_cycle.planning.values", "SELECTOR_ID"),
    ("autonomy.decision.action_plan", "select_action_plan", "autonomy.decision_cycle.planning.selector", "select_highest_confidence_plan"),
    ("autonomy.decision.action_proposal", "ACTION_PROPOSAL_SCHEMA", "autonomy.decision_cycle.proposal.values", "ACTION_PROPOSAL_SCHEMA"),
    ("autonomy.decision.action_proposal", "ActionProposal", "autonomy.decision_cycle.proposal.values", "ActionProposal"),
    ("autonomy.decision.action_proposal", "COMMAND_EPS", "autonomy.decision_cycle.proposal.values", "COMMAND_EPS"),
    ("autonomy.decision.action_proposal", "FRESHNESS_VALUES", "autonomy.decision_cycle.proposal.values", "FRESHNESS_VALUES"),
    ("autonomy.decision.action_proposal", "Freshness", "autonomy.decision_cycle.proposal.values", "Freshness"),
    ("autonomy.decision.action_proposal", "LIFECYCLES", "autonomy.decision_cycle.proposal.values", "LIFECYCLES"),
    ("autonomy.decision.action_proposal", "Lifecycle", "autonomy.decision_cycle.proposal.values", "Lifecycle"),
    ("autonomy.decision.action_proposal", "MAX_ASSUMPTION", "autonomy.decision_cycle.proposal.values", "MAX_ASSUMPTION"),
    ("autonomy.decision.action_proposal", "MAX_ASSUMPTIONS", "autonomy.decision_cycle.proposal.values", "MAX_ASSUMPTIONS"),
    ("autonomy.decision.action_proposal", "MAX_PROPOSAL_BYTES", "autonomy.decision_cycle.proposal.values", "MAX_PROPOSAL_BYTES"),
    ("autonomy.decision.action_proposal", "MAX_PROPOSAL_METADATA_BYTES", "autonomy.decision_cycle.proposal.values", "MAX_PROPOSAL_METADATA_BYTES"),
    ("autonomy.decision.action_proposal", "MAX_REASON", "autonomy.decision_cycle.proposal.values", "MAX_REASON"),
    ("autonomy.decision.action_proposal", "MAX_SOURCE_REFS", "autonomy.decision_cycle.proposal.values", "MAX_SOURCE_REFS"),
    ("autonomy.decision.action_proposal", "MAX_SOURCE_REF_ID", "autonomy.decision_cycle.proposal.values", "MAX_SOURCE_REF_ID"),
    ("autonomy.decision.action_proposal", "MAX_SOURCE_REF_NOTE", "autonomy.decision_cycle.proposal.values", "MAX_SOURCE_REF_NOTE"),
    ("autonomy.decision.action_proposal", "PROPOSED_VEHICLE_COMMAND_SCHEMA", "autonomy.decision_cycle.proposal.values", "PROPOSED_VEHICLE_COMMAND_SCHEMA"),
    ("autonomy.decision.action_proposal", "ProposedVehicleCommand", "autonomy.decision_cycle.proposal.values", "ProposedVehicleCommand"),
    ("autonomy.decision.action_proposal", "SourceRef", "autonomy.decision_cycle.proposal.values", "SourceRef"),
    ("autonomy.decision.action_proposal", "synthetic_error_proposal", "autonomy.decision_cycle.proposal.values", "synthetic_error_proposal"),
    ("autonomy.decision.activation", "ActivatedMemoryStep", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.decision.activation", "DEFAULT_EVICTION_POLICY", "autonomy.decision_cycle.memory.activation", "DEFAULT_EVICTION_POLICY"),
    ("autonomy.decision.activation", "DEFAULT_MAX_AGE_MS", "autonomy.decision_cycle.memory.activation", "DEFAULT_MAX_AGE_MS"),
    ("autonomy.decision.activation", "DEFAULT_MAX_RECORDS", "autonomy.decision_cycle.memory.activation", "DEFAULT_MAX_RECORDS"),
    ("autonomy.decision.activation", "FALLBACK_COUNTER_WIDTH", "autonomy.decision_cycle.memory.snapshots.fallback", "FALLBACK_COUNTER_WIDTH"),
    ("autonomy.decision.activation", "FRAMEWORK_FALLBACK_IMPLEMENTATION_ID", "autonomy.decision_cycle.memory.snapshots.fallback", "FRAMEWORK_FALLBACK_IMPLEMENTATION_ID"),
    ("autonomy.decision.activation", "MAX_FALLBACK_TIMESTAMP_MS", "autonomy.decision_cycle.memory.snapshots.fallback", "MAX_FALLBACK_TIMESTAMP_MS"),
    ("autonomy.decision.activation", "MEMORY_ACTIVATION_SCHEMA", "autonomy.decision_cycle.memory.activation", "MEMORY_ACTIVATION_SCHEMA"),
    ("autonomy.decision.activation", "MemoryActivation", "autonomy.decision_cycle.memory.activation", "MemoryActivation"),
    ("autonomy.decision.activation", "bounds_from_config", "autonomy.decision_cycle.memory.activation", "bounds_from_config"),
    ("autonomy.decision.activation", "build_minimal_framework_fallback", "autonomy.decision_cycle.memory.snapshots.fallback", "build_minimal_framework_fallback"),
    ("autonomy.decision.activation", "framework_error_identity", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_error_identity"),
    ("autonomy.decision.activation", "framework_fallback_timestamp_ms", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_fallback_timestamp_ms"),
    ("autonomy.decision.activation", "framework_reset_identity", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_reset_identity"),
    ("autonomy.decision.activation", "instantiate_memory_implementation", "autonomy.decision_cycle.memory.activation", "instantiate_memory_implementation"),
    ("autonomy.decision.activation", "json_load_object", "autonomy.decision_cycle.memory.activation", "json_load_object"),
    ("autonomy.decision.activation", "load_memory_implementation", "autonomy.decision_cycle.memory.activation", "load_memory_implementation"),
    ("autonomy.decision.activation", "load_memory_step_if_present", "autonomy.decision_cycle.memory.activation", "load_memory_step_if_present"),
    ("autonomy.decision.activation", "memory_manager_from_activation", "autonomy.decision_cycle.memory.activation", "memory_manager_from_activation"),
    ("autonomy.decision.activation", "memory_selection_config", "autonomy.decision_cycle.memory.activation", "memory_selection_config"),
    ("autonomy.decision.activation", "read_memory_activation", "autonomy.decision_cycle.memory.activation", "read_memory_activation"),
    ("autonomy.decision.activation", "validate_framework_fallback_capacity", "autonomy.decision_cycle.memory.snapshots.fallback", "validate_framework_fallback_capacity"),
    ("autonomy.decision.cycle", "DecisionCycle", "autonomy.decision.cycle", "DecisionCycle"),
    ("autonomy.decision.cycle", "DecisionFrameContext", "autonomy.decision_cycle.context", "DecisionFrameContext"),
    ("autonomy.decision.cycle", "MemoryUpdateError", "autonomy.decision_cycle.memory.errors", "MemoryUpdateError"),
    ("autonomy.decision.decision_data", "CAPABILITY_REQUIRED_KEYS", "autonomy.decision_cycle.proposal.inputs", "CAPABILITY_REQUIRED_KEYS"),
    ("autonomy.decision.decision_data", "COMPONENT_STATUSES", "autonomy.decision_cycle.proposal.inputs", "COMPONENT_STATUSES"),
    ("autonomy.decision.decision_data", "ComponentEnvelope", "autonomy.decision_cycle.proposal.inputs", "ComponentEnvelope"),
    ("autonomy.decision.decision_data", "ComponentStatus", "autonomy.decision_cycle.proposal.inputs", "ComponentStatus"),
    ("autonomy.decision.decision_data", "DECISION_DATA_SOURCE_SCHEMA", "autonomy.decision_cycle.proposal.inputs", "DECISION_DATA_SOURCE_SCHEMA"),
    ("autonomy.decision.decision_data", "DecisionDataSource", "autonomy.decision_cycle.proposal.inputs", "DecisionDataSource"),
    ("autonomy.decision.decision_data", "FORBIDDEN_CHANNEL_ORIGINS", "autonomy.decision_cycle.proposal.inputs", "FORBIDDEN_CHANNEL_ORIGINS"),
    ("autonomy.decision.decision_data", "MAX_ENVELOPE_REASON", "autonomy.decision_cycle.proposal.inputs", "MAX_ENVELOPE_REASON"),
    ("autonomy.decision.decision_data", "MAX_SOURCE_METADATA_BYTES", "autonomy.decision_cycle.proposal.inputs", "MAX_SOURCE_METADATA_BYTES"),
    ("autonomy.decision.decision_data", "PRIOR_HOST_ALLOWED_KEYS", "autonomy.decision_cycle.proposal.inputs", "PRIOR_HOST_ALLOWED_KEYS"),
    ("autonomy.decision.decision_data", "build_decision_data_source", "autonomy.decision_cycle.proposal.inputs", "build_decision_data_source"),
    ("autonomy.decision.decision_data", "default_capabilities", "autonomy.decision_cycle.proposal.inputs", "default_capabilities"),
    ("autonomy.decision.decision_data", "empty_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "empty_memory_snapshot"),
    ("autonomy.decision.decision_data", "error_envelope", "autonomy.decision_cycle.proposal.inputs", "error_envelope"),
    ("autonomy.decision.decision_data", "memory_envelope_from_snapshot", "autonomy.decision_cycle.proposal.inputs", "memory_envelope_from_snapshot"),
    ("autonomy.decision.decision_data", "observation_envelope_from_value", "autonomy.decision_cycle.proposal.inputs", "observation_envelope_from_value"),
    ("autonomy.decision.decision_data", "omit_forbidden_channel_keys", "autonomy.decision_cycle.proposal.inputs", "omit_forbidden_channel_keys"),
    ("autonomy.decision.decision_data", "ready_envelope", "autonomy.decision_cycle.proposal.inputs", "ready_envelope"),
    ("autonomy.decision.decision_data", "unavailable_envelope", "autonomy.decision_cycle.proposal.inputs", "unavailable_envelope"),
    ("autonomy.decision.memory", "DEFAULT_MAX_DIAGNOSTIC_CHARS", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_DIAGNOSTIC_CHARS"),
    ("autonomy.decision.memory", "DEFAULT_MAX_PROPERTY_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_PROPERTY_BYTES"),
    ("autonomy.decision.memory", "DEFAULT_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_SERIALIZED_BYTES"),
    ("autonomy.decision.memory", "MEMORY_HEALTH_VALUES", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_HEALTH_VALUES"),
    ("autonomy.decision.memory", "MEMORY_SNAPSHOT_SCHEMA", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_SNAPSHOT_SCHEMA"),
    ("autonomy.decision.memory", "MIN_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "MIN_MAX_SERIALIZED_BYTES"),
    ("autonomy.decision.memory", "MemoryBounds", "autonomy.decision_cycle.memory.snapshots.values", "MemoryBounds"),
    ("autonomy.decision.memory", "MemoryHealth", "autonomy.decision_cycle.memory.snapshots.values", "MemoryHealth"),
    ("autonomy.decision.memory", "MemoryProvenance", "autonomy.decision_cycle.memory.snapshots.values", "MemoryProvenance"),
    ("autonomy.decision.memory", "MemorySnapshot", "autonomy.decision_cycle.memory.snapshots.values", "MemorySnapshot"),
    ("autonomy.decision.memory", "RetainedEvidence", "autonomy.decision_cycle.memory.snapshots.values", "RetainedEvidence"),
    ("autonomy.decision.memory", "canonical_json_bytes", "autonomy.serialization", "canonical_json_size_bytes"),
    ("autonomy.decision.memory", "canonical_json_utf8", "autonomy.serialization", "canonical_json_utf8"),
    ("autonomy.decision.memory", "detach_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "detach_memory_snapshot"),
    ("autonomy.decision.memory", "empty_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "empty_memory_snapshot"),
    ("autonomy.decision.memory", "ensure_strict_json_value", "autonomy.serialization", "ensure_strict_json_value"),
    ("autonomy.decision.memory", "error_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "error_memory_snapshot"),
    ("autonomy.decision.memory", "serialized_mapping_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_mapping_bytes"),
    ("autonomy.decision.memory", "serialized_memory_snapshot_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_memory_snapshot_bytes"),
    ("autonomy.decision.memory", "unavailable_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "unavailable_memory_snapshot"),
    ("autonomy.decision.observation", "OBSERVATION_SCHEMA", "autonomy.decision_cycle.observation.values", "OBSERVATION_SCHEMA"),
    ("autonomy.decision.observation", "Observation", "autonomy.decision_cycle.observation.values", "Observation"),
    ("autonomy.decision.observation", "observation_from_perception", "autonomy.decision_cycle.observation.step", "observation_from_perception"),
    ("autonomy.decision.observation", "timestamp_ms", "autonomy.decision_cycle.observation.step", "timestamp_ms"),
    ("autonomy.decision.plugin", "MemoryImplementation", "autonomy.decision_cycle.memory.plugin", "MemoryImplementation"),
    ("autonomy.decision.shadow_authority", "AUTHORIZED_IDLE_REASON", "autonomy.decision_cycle.action_gate.hold", "AUTHORIZED_IDLE_REASON"),
    ("autonomy.decision.shadow_authority", "COMMAND_EPS", "autonomy.decision_cycle.action_gate.hold", "COMMAND_EPS"),
    ("autonomy.decision.shadow_authority", "ENGINE_ERROR_REASONS", "autonomy.decision_cycle.errors", "ENGINE_ERROR_REASONS"),
    ("autonomy.decision.shadow_authority", "SHADOW_AUTHORITY_RESULT_SCHEMA", "autonomy.decision_cycle.action_gate.hold", "SHADOW_AUTHORITY_RESULT_SCHEMA"),
    ("autonomy.decision.shadow_authority", "SHADOW_DECISION_CYCLE_RESULT_SCHEMA", "autonomy.decision_cycle.result", "SHADOW_DECISION_CYCLE_RESULT_SCHEMA"),
    ("autonomy.decision.shadow_authority", "ShadowAuthorityResult", "autonomy.decision_cycle.action_gate.hold", "ShadowAuthorityResult"),
    ("autonomy.decision.shadow_authority", "ShadowDecisionCycleResult", "autonomy.decision_cycle.result", "ShadowDecisionCycleResult"),
    ("autonomy.decision.shadow_authority", "authorized_idle_control", "autonomy.decision_cycle.action_gate.hold", "authorized_idle_control"),
    ("autonomy.decision.shadow_authority", "authorized_idle_output", "autonomy.decision_cycle.action_gate.hold", "authorized_idle_output"),
    ("autonomy.decision.shadow_authority", "build_authority", "autonomy.decision_cycle.action_gate.hold", "build_authority"),
    ("autonomy.decision.shadow_authority", "proposed_equals_authorized", "autonomy.decision_cycle.action_gate.hold", "proposed_equals_authorized"),
    ("autonomy.decision.shadow_ids", "ActionProposalMatrixError", "autonomy.decision_cycle.action_identifiers", "ActionProposalMatrixError"),
    ("autonomy.decision.shadow_ids", "FrozenJsonObject", "autonomy.serialization", "FrozenJsonObject"),
    ("autonomy.decision.shadow_ids", "IDENTIFIER_PATTERN", "autonomy.decision_cycle.action_identifiers", "IDENTIFIER_PATTERN"),
    ("autonomy.decision.shadow_ids", "MAX_ID_LEN", "autonomy.decision_cycle.action_identifiers", "MAX_ID_LEN"),
    ("autonomy.decision.shadow_ids", "MAX_SAFE_INT", "autonomy.decision_cycle.action_identifiers", "MAX_SAFE_INT"),
    ("autonomy.decision.shadow_ids", "ShadowCycleInputError", "autonomy.decision_cycle.action_identifiers", "ShadowCycleInputError"),
    ("autonomy.decision.shadow_ids", "deep_freeze", "autonomy.serialization", "deep_freeze"),
    ("autonomy.decision.shadow_ids", "frozen_mapping_to_dict", "autonomy.serialization", "frozen_mapping_to_dict"),
    ("autonomy.decision.shadow_ids", "plan_id_for", "autonomy.decision_cycle.action_identifiers", "plan_id_for"),
    ("autonomy.decision.shadow_ids", "proposal_id_for", "autonomy.decision_cycle.action_identifiers", "proposal_id_for"),
    ("autonomy.decision.shadow_ids", "require_ascii_id", "autonomy.decision_cycle.action_identifiers", "require_ascii_id"),
    ("autonomy.decision.shadow_ids", "require_code_point_len", "autonomy.decision_cycle.action_identifiers", "require_code_point_len"),
    ("autonomy.decision.shadow_ids", "require_safe_int", "autonomy.decision_cycle.action_identifiers", "require_safe_int"),
    ("autonomy.decision.shadow_runner", "ENGINE_ID", "autonomy.decision_cycle.action", "ENGINE_ID"),
    ("autonomy.decision.shadow_runner", "ProposalPlugin", "autonomy.decision_cycle.action", "ProposalPlugin"),
    ("autonomy.decision.shadow_runner", "ShadowProposalsConfig", "autonomy.decision_cycle.action", "ShadowProposalsConfig"),
    ("autonomy.decision.shadow_runner", "ShadowProposalsEngine", "autonomy.decision_cycle.action", "ShadowProposalsEngine"),

    # autonomy.memory
    ("autonomy.memory", "ActivatedMemoryStep", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.memory", "DEFAULT_MAX_DIAGNOSTIC_CHARS", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_DIAGNOSTIC_CHARS"),
    ("autonomy.memory", "DEFAULT_MAX_PROPERTY_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_PROPERTY_BYTES"),
    ("autonomy.memory", "DEFAULT_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_SERIALIZED_BYTES"),
    ("autonomy.memory", "MEMORY_ACTIVATION_SCHEMA", "autonomy.decision_cycle.memory.activation", "MEMORY_ACTIVATION_SCHEMA"),
    ("autonomy.memory", "MEMORY_HEALTH_VALUES", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_HEALTH_VALUES"),
    ("autonomy.memory", "MEMORY_SNAPSHOT_SCHEMA", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_SNAPSHOT_SCHEMA"),
    ("autonomy.memory", "MIN_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "MIN_MAX_SERIALIZED_BYTES"),
    ("autonomy.memory", "MemoryActivation", "autonomy.decision_cycle.memory.activation", "MemoryActivation"),
    ("autonomy.memory", "MemoryBounds", "autonomy.decision_cycle.memory.snapshots.values", "MemoryBounds"),
    ("autonomy.memory", "MemoryHealth", "autonomy.decision_cycle.memory.snapshots.values", "MemoryHealth"),
    ("autonomy.memory", "MemoryImplementation", "autonomy.decision_cycle.memory.plugin", "MemoryImplementation"),
    ("autonomy.memory", "MemoryProvenance", "autonomy.decision_cycle.memory.snapshots.values", "MemoryProvenance"),
    ("autonomy.memory", "MemorySnapshot", "autonomy.decision_cycle.memory.snapshots.values", "MemorySnapshot"),
    ("autonomy.memory", "PluginMemoryRunner", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.memory", "RetainedEvidence", "autonomy.decision_cycle.memory.snapshots.values", "RetainedEvidence"),
    ("autonomy.memory", "SharedMemory", "autonomy.shared_memory", "SharedMemory"),
    ("autonomy.memory", "canonical_json_bytes", "autonomy.serialization", "canonical_json_size_bytes"),
    ("autonomy.memory", "canonical_json_utf8", "autonomy.serialization", "canonical_json_utf8"),
    ("autonomy.memory", "detach_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "detach_memory_snapshot"),
    ("autonomy.memory", "empty_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "empty_memory_snapshot"),
    ("autonomy.memory", "ensure_strict_json_value", "autonomy.serialization", "ensure_strict_json_value"),
    ("autonomy.memory", "error_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "error_memory_snapshot"),
    ("autonomy.memory", "instantiate_memory_implementation", "autonomy.decision_cycle.memory.activation", "instantiate_memory_implementation"),
    ("autonomy.memory", "load_memory_implementation", "autonomy.decision_cycle.memory.activation", "load_memory_implementation"),
    ("autonomy.memory", "load_memory_step_if_present", "autonomy.decision_cycle.memory.activation", "load_memory_step_if_present"),
    ("autonomy.memory", "read_memory_activation", "autonomy.decision_cycle.memory.activation", "read_memory_activation"),
    ("autonomy.memory", "serialized_mapping_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_mapping_bytes"),
    ("autonomy.memory", "serialized_memory_snapshot_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_memory_snapshot_bytes"),
    ("autonomy.memory", "unavailable_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "unavailable_memory_snapshot"),
    ("autonomy.memory.activation", "ActivatedMemoryStep", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.memory.activation", "DEFAULT_EVICTION_POLICY", "autonomy.decision_cycle.memory.activation", "DEFAULT_EVICTION_POLICY"),
    ("autonomy.memory.activation", "DEFAULT_MAX_AGE_MS", "autonomy.decision_cycle.memory.activation", "DEFAULT_MAX_AGE_MS"),
    ("autonomy.memory.activation", "DEFAULT_MAX_RECORDS", "autonomy.decision_cycle.memory.activation", "DEFAULT_MAX_RECORDS"),
    ("autonomy.memory.activation", "FALLBACK_COUNTER_WIDTH", "autonomy.decision_cycle.memory.snapshots.fallback", "FALLBACK_COUNTER_WIDTH"),
    ("autonomy.memory.activation", "FRAMEWORK_FALLBACK_IMPLEMENTATION_ID", "autonomy.decision_cycle.memory.snapshots.fallback", "FRAMEWORK_FALLBACK_IMPLEMENTATION_ID"),
    ("autonomy.memory.activation", "MAX_FALLBACK_TIMESTAMP_MS", "autonomy.decision_cycle.memory.snapshots.fallback", "MAX_FALLBACK_TIMESTAMP_MS"),
    ("autonomy.memory.activation", "MEMORY_ACTIVATION_SCHEMA", "autonomy.decision_cycle.memory.activation", "MEMORY_ACTIVATION_SCHEMA"),
    ("autonomy.memory.activation", "MemoryActivation", "autonomy.decision_cycle.memory.activation", "MemoryActivation"),
    ("autonomy.memory.activation", "PluginMemoryRunner", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.memory.activation", "bounds_from_config", "autonomy.decision_cycle.memory.activation", "bounds_from_config"),
    ("autonomy.memory.activation", "build_minimal_framework_fallback", "autonomy.decision_cycle.memory.snapshots.fallback", "build_minimal_framework_fallback"),
    ("autonomy.memory.activation", "framework_error_identity", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_error_identity"),
    ("autonomy.memory.activation", "framework_fallback_timestamp_ms", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_fallback_timestamp_ms"),
    ("autonomy.memory.activation", "framework_reset_identity", "autonomy.decision_cycle.memory.snapshots.fallback", "framework_reset_identity"),
    ("autonomy.memory.activation", "instantiate_memory_implementation", "autonomy.decision_cycle.memory.activation", "instantiate_memory_implementation"),
    ("autonomy.memory.activation", "json_load_object", "autonomy.decision_cycle.memory.activation", "json_load_object"),
    ("autonomy.memory.activation", "load_memory_implementation", "autonomy.decision_cycle.memory.activation", "load_memory_implementation"),
    ("autonomy.memory.activation", "load_memory_step_if_present", "autonomy.decision_cycle.memory.activation", "load_memory_step_if_present"),
    ("autonomy.memory.activation", "memory_manager_from_activation", "autonomy.decision_cycle.memory.activation", "memory_manager_from_activation"),
    ("autonomy.memory.activation", "memory_selection_config", "autonomy.decision_cycle.memory.activation", "memory_selection_config"),
    ("autonomy.memory.activation", "read_memory_activation", "autonomy.decision_cycle.memory.activation", "read_memory_activation"),
    ("autonomy.memory.activation", "validate_framework_fallback_capacity", "autonomy.decision_cycle.memory.snapshots.fallback", "validate_framework_fallback_capacity"),
    ("autonomy.memory.plugin", "MemoryImplementation", "autonomy.decision_cycle.memory.plugin", "MemoryImplementation"),
    ("autonomy.memory.plugin_runner", "PluginMemoryRunner", "autonomy.decision_cycle.memory.plugin_runner", "PluginMemoryRunner"),
    ("autonomy.memory.plugin_runner", "format_exception_safely", "autonomy.decision_cycle.memory.execution.plugin_runtime", "format_exception_safely"),
    ("autonomy.memory.selection", "memory_plugin_manager", "autonomy.decision_cycle.memory.selection", "memory_plugin_manager"),
    ("autonomy.memory.values", "DEFAULT_MAX_DIAGNOSTIC_CHARS", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_DIAGNOSTIC_CHARS"),
    ("autonomy.memory.values", "DEFAULT_MAX_PROPERTY_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_PROPERTY_BYTES"),
    ("autonomy.memory.values", "DEFAULT_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "DEFAULT_MAX_SERIALIZED_BYTES"),
    ("autonomy.memory.values", "MEMORY_HEALTH_VALUES", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_HEALTH_VALUES"),
    ("autonomy.memory.values", "MEMORY_SNAPSHOT_SCHEMA", "autonomy.decision_cycle.memory.snapshots.values", "MEMORY_SNAPSHOT_SCHEMA"),
    ("autonomy.memory.values", "MIN_MAX_SERIALIZED_BYTES", "autonomy.decision_cycle.memory.snapshots.values", "MIN_MAX_SERIALIZED_BYTES"),
    ("autonomy.memory.values", "MemoryBounds", "autonomy.decision_cycle.memory.snapshots.values", "MemoryBounds"),
    ("autonomy.memory.values", "MemoryHealth", "autonomy.decision_cycle.memory.snapshots.values", "MemoryHealth"),
    ("autonomy.memory.values", "MemoryProvenance", "autonomy.decision_cycle.memory.snapshots.values", "MemoryProvenance"),
    ("autonomy.memory.values", "MemorySnapshot", "autonomy.decision_cycle.memory.snapshots.values", "MemorySnapshot"),
    ("autonomy.memory.values", "RetainedEvidence", "autonomy.decision_cycle.memory.snapshots.values", "RetainedEvidence"),
    ("autonomy.memory.values", "canonical_json_bytes", "autonomy.serialization", "canonical_json_bytes"),
    ("autonomy.memory.values", "canonical_json_utf8", "autonomy.serialization", "canonical_json_utf8"),
    ("autonomy.memory.values", "detach_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "detach_memory_snapshot"),
    ("autonomy.memory.values", "empty_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "empty_memory_snapshot"),
    ("autonomy.memory.values", "ensure_strict_json_value", "autonomy.serialization", "ensure_strict_json_value"),
    ("autonomy.memory.values", "error_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "error_memory_snapshot"),
    ("autonomy.memory.values", "serialized_mapping_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_mapping_bytes"),
    ("autonomy.memory.values", "serialized_memory_snapshot_bytes", "autonomy.decision_cycle.memory.snapshots.values", "serialized_memory_snapshot_bytes"),
    ("autonomy.memory.values", "unavailable_memory_snapshot", "autonomy.decision_cycle.memory.snapshots.values", "unavailable_memory_snapshot"),

    # autonomy.serialization
    ("autonomy.serialization", "FrozenJsonObject", "autonomy.serialization", "FrozenJsonObject"),
    ("autonomy.serialization", "canonical_json_bytes", "autonomy.serialization", "canonical_json_size_bytes"),
    ("autonomy.serialization", "canonical_json_size_bytes", "autonomy.serialization", "canonical_json_size_bytes"),
    ("autonomy.serialization", "canonical_json_utf8", "autonomy.serialization", "canonical_json_utf8"),
    ("autonomy.serialization", "deep_freeze", "autonomy.serialization", "deep_freeze"),
    ("autonomy.serialization", "ensure_strict_json_value", "autonomy.serialization", "ensure_strict_json_value"),
    ("autonomy.serialization", "frozen_mapping_to_dict", "autonomy.serialization", "frozen_mapping_to_dict"),

    # autonomy.perception
    ("autonomy.perception", "ActivatedPerceptionStep", "autonomy.decision_cycle.perception.activation", "ActivatedPerceptionStep"),
    ("autonomy.perception", "PERCEPTION_ACTIVATION_SCHEMA", "autonomy.decision_cycle.perception.activation", "PERCEPTION_ACTIVATION_SCHEMA"),
    ("autonomy.perception", "PERCEPTION_TEXT_SCHEMA", "autonomy.decision_cycle.perception.interface", "PERCEPTION_TEXT_SCHEMA"),
    ("autonomy.perception", "PerceivedThing", "autonomy.decision_cycle.perception.evidence.values", "PerceivedThing"),
    ("autonomy.perception", "PerceptionActivation", "autonomy.decision_cycle.perception.activation", "PerceptionActivation"),
    ("autonomy.perception", "PerceptionComponentUnavailable", "autonomy.decision_cycle.perception.components.interface", "PerceptionComponentUnavailable"),
    ("autonomy.perception", "PerceptionDiagnosticSink", "autonomy.decision_cycle.perception.diagnostics.sink", "PerceptionDiagnosticSink"),
    ("autonomy.perception", "PerceptionEvidenceBatch", "autonomy.decision_cycle.perception.evidence.values", "PerceptionEvidenceBatch"),
    ("autonomy.perception", "PerceptionMapper", "autonomy.decision_cycle.perception.interface", "PerceptionMapper"),
    ("autonomy.perception", "PerceptionPlugin", "autonomy.decision_cycle.perception.plugin", "PerceptionPlugin"),
    ("autonomy.perception", "PerceptionPluginContract", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginContract"),
    ("autonomy.perception", "PerceptionPluginInput", "autonomy.decision_cycle.perception.components.interface", "PerceptionPluginInput"),
    ("autonomy.perception", "PerceptionPluginInputs", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginInputs"),
    ("autonomy.perception", "PerceptionPluginRun", "autonomy.decision_cycle.perception.interface", "PerceptionPluginRun"),
    ("autonomy.perception", "PerceptionPluginWarmingUp", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginWarmingUp"),
    ("autonomy.perception", "PerceptionRequest", "autonomy.decision_cycle.perception.components.context", "PerceptionRequest"),
    ("autonomy.perception", "PerceptionSignal", "autonomy.decision_cycle.perception.evidence.values", "PerceptionSignal"),
    ("autonomy.perception", "PerceptionText", "autonomy.decision_cycle.perception.interface", "PerceptionText"),
    ("autonomy.perception", "ViewLocation", "autonomy.decision_cycle.perception.evidence.values", "ViewLocation"),
    ("autonomy.perception", "build_perception_request", "autonomy.decision_cycle.perception.inputs", "build_perception_request"),
    ("autonomy.perception", "instantiate_perception_mapper", "autonomy.decision_cycle.perception.activation", "instantiate_perception_mapper"),
    ("autonomy.perception", "load_perception_mapper", "autonomy.decision_cycle.perception.activation", "load_perception_mapper"),
    ("autonomy.perception", "read_perception_activation", "autonomy.decision_cycle.perception.activation", "read_perception_activation"),
    ("autonomy.perception.activation", "ActivatedPerceptionStep", "autonomy.decision_cycle.perception.activation", "ActivatedPerceptionStep"),
    ("autonomy.perception.activation", "PERCEPTION_ACTIVATION_SCHEMA", "autonomy.decision_cycle.perception.activation", "PERCEPTION_ACTIVATION_SCHEMA"),
    ("autonomy.perception.activation", "PerceptionActivation", "autonomy.decision_cycle.perception.activation", "PerceptionActivation"),
    ("autonomy.perception.activation", "instantiate_perception_mapper", "autonomy.decision_cycle.perception.activation", "instantiate_perception_mapper"),
    ("autonomy.perception.activation", "load_perception_mapper", "autonomy.decision_cycle.perception.activation", "load_perception_mapper"),
    ("autonomy.perception.activation", "read_perception_activation", "autonomy.decision_cycle.perception.activation", "read_perception_activation"),
    ("autonomy.perception.evidence", "PerceivedThing", "autonomy.decision_cycle.perception.evidence.values", "PerceivedThing"),
    ("autonomy.perception.evidence", "PerceptionEvidenceBatch", "autonomy.decision_cycle.perception.evidence.values", "PerceptionEvidenceBatch"),
    ("autonomy.perception.evidence", "PerceptionSignal", "autonomy.decision_cycle.perception.evidence.values", "PerceptionSignal"),
    ("autonomy.perception.evidence", "ViewLocation", "autonomy.decision_cycle.perception.evidence.values", "ViewLocation"),
    ("autonomy.perception.inputs", "build_perception_request", "autonomy.decision_cycle.perception.inputs", "build_perception_request"),
    ("autonomy.perception.interface", "ComponentT", "autonomy.decision_cycle.perception.components.context", "ComponentT"),
    ("autonomy.perception.interface", "PERCEPTION_TEXT_SCHEMA", "autonomy.decision_cycle.perception.interface", "PERCEPTION_TEXT_SCHEMA"),
    ("autonomy.perception.interface", "PLUGIN_RESULT_STATUSES", "autonomy.decision_cycle.perception.interface", "PLUGIN_RESULT_STATUSES"),
    ("autonomy.perception.interface", "PerceptionMapper", "autonomy.decision_cycle.perception.interface", "PerceptionMapper"),
    ("autonomy.perception.interface", "PerceptionPluginRun", "autonomy.decision_cycle.perception.interface", "PerceptionPluginRun"),
    ("autonomy.perception.interface", "PerceptionRequest", "autonomy.decision_cycle.perception.components.context", "PerceptionRequest"),
    ("autonomy.perception.interface", "PerceptionText", "autonomy.decision_cycle.perception.interface", "PerceptionText"),
    ("autonomy.perception.interface", "PluginResultStatus", "autonomy.decision_cycle.perception.interface", "PluginResultStatus"),
    ("autonomy.perception.mappers", "PluginPerceptionMapper", "autonomy.decision_cycle.perception.plugin_runner", "PluginPerceptionMapper"),
    ("autonomy.perception.mappers.plugin_runner", "PluginPerceptionMapper", "autonomy.decision_cycle.perception.plugin_runner", "PluginPerceptionMapper"),
    ("autonomy.perception.plugin", "ComponentT", "autonomy.decision_cycle.perception.plugin", "ComponentT"),
    ("autonomy.perception.plugin", "PLUGIN_STATE_MODES", "autonomy.decision_cycle.perception.plugin", "PLUGIN_STATE_MODES"),
    ("autonomy.perception.plugin", "PerceptionComponentUnavailable", "autonomy.decision_cycle.perception.components.interface", "PerceptionComponentUnavailable"),
    ("autonomy.perception.plugin", "PerceptionDiagnosticSink", "autonomy.decision_cycle.perception.diagnostics.sink", "PerceptionDiagnosticSink"),
    ("autonomy.perception.plugin", "PerceptionPlugin", "autonomy.decision_cycle.perception.plugin", "PerceptionPlugin"),
    ("autonomy.perception.plugin", "PerceptionPluginContract", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginContract"),
    ("autonomy.perception.plugin", "PerceptionPluginInput", "autonomy.decision_cycle.perception.components.interface", "PerceptionPluginInput"),
    ("autonomy.perception.plugin", "PerceptionPluginInputs", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginInputs"),
    ("autonomy.perception.plugin", "PerceptionPluginWarmingUp", "autonomy.decision_cycle.perception.plugin", "PerceptionPluginWarmingUp"),
    ("autonomy.perception.plugin", "PluginStateMode", "autonomy.decision_cycle.perception.plugin", "PluginStateMode"),
    ("autonomy.perception.plugin_runner", "ComponentProvider", "autonomy.decision_cycle.perception.components.interface", "ComponentProvider"),
    ("autonomy.perception.plugin_runner", "PluginPerceptionMapper", "autonomy.decision_cycle.perception.plugin_runner", "PluginPerceptionMapper"),
    ("autonomy.perception.rendering", "signal_line", "autonomy.decision_cycle.perception.evidence.rendering", "signal_line"),
    ("autonomy.perception.rendering", "thing_line", "autonomy.decision_cycle.perception.evidence.rendering", "thing_line"),
    ("autonomy.perception.selection", "perception_plugin_manager", "autonomy.decision_cycle.perception.selection", "perception_plugin_manager"),

    # autonomy.runtime
    ("autonomy.runtime", "AutonomyControl", "autonomy.runtime.engine", "AutonomyControl"),
    ("autonomy.runtime", "AutonomyManager", "autonomy.runtime.manager", "AutonomyManager"),
    ("autonomy.runtime", "AutonomySnapshot", "autonomy.runtime.engine", "AutonomySnapshot"),
    ("autonomy.runtime", "DECISION_ACTIVATION_SCHEMA", "autonomy.runtime.activation", "DECISION_ACTIVATION_SCHEMA"),
    ("autonomy.runtime", "DecisionActivation", "autonomy.runtime.activation", "DecisionActivation"),
    ("autonomy.runtime", "IdleAutonomyEngine", "autonomy.runtime.engine", "IdleAutonomyEngine"),
    ("autonomy.runtime", "apply_decision_activation", "autonomy.runtime.activation", "apply_decision_activation"),
    ("autonomy.runtime", "read_decision_activation", "autonomy.runtime.activation", "read_decision_activation"),

    # autonomy.shared_memory
    ("autonomy.shared_memory", "SharedMemory", "autonomy.shared_memory", "SharedMemory"),

    # autonomy.vehicle
    ("autonomy.vehicle", "CarInterface", "autonomy.vehicle.vehicle", "CarInterface"),
    ("autonomy.vehicle", "FRONT_CAMERA_SENSOR_ID", "autonomy.vehicle.vehicle", "FRONT_CAMERA_SENSOR_ID"),
    ("autonomy.vehicle", "SensorReadRequest", "autonomy.vehicle.vehicle", "SensorReadRequest"),
    ("autonomy.vehicle", "SensorReading", "autonomy.vehicle.vehicle", "SensorReading"),
    ("autonomy.vehicle", "SensorSnapshot", "autonomy.vehicle.vehicle", "SensorSnapshot"),
    ("autonomy.vehicle", "VEHICLE_ACTION_FIELDS", "autonomy.vehicle.vehicle", "VEHICLE_ACTION_FIELDS"),
    ("autonomy.vehicle", "VehicleAction", "autonomy.vehicle.vehicle", "VehicleAction"),
    ("autonomy.vehicle", "VehicleCapabilities", "autonomy.vehicle.vehicle", "VehicleCapabilities"),
    ("autonomy.vehicle", "VehiclePulse", "autonomy.vehicle.vehicle", "VehiclePulse"),
    ("autonomy.vehicle", "clamp_unit", "autonomy.vehicle.vehicle", "clamp_unit"),

    # implementations.memory
    ("implementations.memory", "BoundedEvidenceLedger", "implementations.decision_cycle.memory.bounded_evidence.plugin", "BoundedEvidenceLedger"),
    ("implementations.memory", "DEFAULT_MEMORY_IMPLEMENTATION", "implementations.decision_cycle.memory.catalog", "DEFAULT_MEMORY_IMPLEMENTATION"),
    ("implementations.memory", "MEMORY_IMPLEMENTATIONS", "implementations.decision_cycle.memory.catalog", "MEMORY_IMPLEMENTATIONS"),
    ("implementations.memory", "available_memory_implementation_ids", "implementations.decision_cycle.memory.catalog", "available_memory_implementation_ids"),
    ("implementations.memory", "build_memory_activation_payload", "implementations.decision_cycle.memory.catalog", "build_memory_activation_payload"),
    ("implementations.memory", "memory_implementation_spec", "implementations.decision_cycle.memory.catalog", "memory_implementation_spec"),
    ("implementations.memory.bounded_evidence", "reduce_evidence", "implementations.decision_cycle.memory.bounded_evidence.plugin", "reduce_evidence"),

    # implementations.operations
    ("implementations.operations", "CapturePulseStep", "implementations.operations.capture_pulse_sequence", "CapturePulseStep"),
    ("implementations.operations", "StartupActionCheckInstruction", "implementations.operations.startup_action_check.types", "StartupActionCheckInstruction"),
    ("implementations.operations", "StartupActionCheckPlan", "implementations.operations.startup_action_check.types", "StartupActionCheckPlan"),
    ("implementations.operations", "build_basic_startup_action_check_plan", "implementations.operations.startup_action_check.plans", "build_basic_startup_action_check_plan"),
    ("implementations.operations", "run_capture_pulse_sequence", "implementations.operations.capture_pulse_sequence", "run_capture_pulse_sequence"),
    ("implementations.operations", "run_startup_action_check", "implementations.operations.startup_action_check.runner", "run_startup_action_check"),
    ("implementations.operations.startup_action_check", "StartupActionCheckInstruction", "implementations.operations.startup_action_check.types", "StartupActionCheckInstruction"),
    ("implementations.operations.startup_action_check", "StartupActionCheckPlan", "implementations.operations.startup_action_check.types", "StartupActionCheckPlan"),
    ("implementations.operations.startup_action_check", "build_basic_startup_action_check_plan", "implementations.operations.startup_action_check.plans", "build_basic_startup_action_check_plan"),
    ("implementations.operations.startup_action_check", "run_startup_action_check", "implementations.operations.startup_action_check.runner", "run_startup_action_check"),

    # implementations.perception
    ("implementations.perception.components", "CameraFrame", "implementations.decision_cycle.perception.components.camera", "CameraFrame"),
    ("implementations.perception.components", "FRONT_CAMERA_RGB_INPUT", "implementations.decision_cycle.perception.components.camera", "FRONT_CAMERA_RGB_INPUT"),
    ("implementations.perception.components", "camera_component_id", "implementations.decision_cycle.perception.components.camera", "camera_component_id"),
    ("implementations.perception.components", "camera_rgb_input", "implementations.decision_cycle.perception.components.camera", "camera_rgb_input"),
    ("implementations.perception.components", "provide_camera_frame", "implementations.decision_cycle.perception.components.camera", "provide_camera_frame"),
    ("implementations.perception.components.camera", "FRONT_CAMERA_RGB_INPUT", "implementations.decision_cycle.perception.components.camera", "FRONT_CAMERA_RGB_INPUT"),
    ("implementations.perception.components.camera", "provide_camera_frame", "implementations.decision_cycle.perception.components.camera", "provide_camera_frame"),
    ("implementations.perception.features", "FeatureMatch", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "FeatureMatch"),
    ("implementations.perception.features", "FeatureTrackingResult", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "FeatureTrackingResult"),
    ("implementations.perception.features", "PairTrackingSummary", "implementations.decision_cycle.perception.algorithms.features.feature_sequence", "PairTrackingSummary"),
    ("implementations.perception.features", "TrackedSequenceSummary", "implementations.decision_cycle.perception.algorithms.features.feature_sequence", "TrackedSequenceSummary"),
    ("implementations.perception.features", "analyze_tracked_sequence", "implementations.decision_cycle.perception.algorithms.features.feature_sequence", "analyze_tracked_sequence"),
    ("implementations.perception.features", "detect_keypoints", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "detect_keypoints"),
    ("implementations.perception.features", "grayscale", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "grayscale"),
    ("implementations.perception.features", "match_keypoints", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "match_keypoints"),
    ("implementations.perception.features", "track_features", "implementations.decision_cycle.perception.algorithms.features.feature_tracking", "track_features"),
    ("implementations.perception.landmarks", "LandmarkDistanceResult", "implementations.decision_cycle.perception.algorithms.landmarks.distance", "LandmarkDistanceResult"),
    ("implementations.perception.landmarks", "LandmarkSelection", "implementations.decision_cycle.perception.algorithms.landmarks.distance", "LandmarkSelection"),
    ("implementations.perception.landmarks", "LandmarkStepEstimate", "implementations.decision_cycle.perception.algorithms.landmarks.distance", "LandmarkStepEstimate"),
    ("implementations.perception.landmarks", "estimate_landmark_distance", "implementations.decision_cycle.perception.algorithms.landmarks.distance", "estimate_landmark_distance"),
    ("implementations.perception.motion", "MotionGroup", "implementations.decision_cycle.perception.algorithms.motion.scene_motion", "MotionGroup"),
    ("implementations.perception.motion", "SceneMotionResult", "implementations.decision_cycle.perception.algorithms.motion.scene_motion", "SceneMotionResult"),
    ("implementations.perception.motion", "analyze_scene_motion", "implementations.decision_cycle.perception.algorithms.motion.scene_motion", "analyze_scene_motion"),
    ("implementations.perception.motion", "analyze_scene_motion_images", "implementations.decision_cycle.perception.algorithms.motion.scene_motion", "analyze_scene_motion_images"),
    ("implementations.perception.motion", "find_motion_groups", "implementations.decision_cycle.perception.algorithms.motion.scene_motion", "find_motion_groups"),
    ("implementations.perception.observation", "FrameObservationPlugin", "implementations.decision_cycle.perception.frame_observation.plugin", "FrameObservationPlugin"),
    ("implementations.perception.observation", "compare_frame_pair", "implementations.decision_cycle.perception.frame_observation.frame_analysis", "compare_frame_pair"),
    ("implementations.perception.observation", "observe_frame", "implementations.decision_cycle.perception.frame_observation.frame_analysis", "observe_frame"),
    ("implementations.perception.observation", "observe_rgb_frame", "implementations.decision_cycle.perception.frame_observation.frame_analysis", "observe_rgb_frame"),
    ("implementations.perception.preparation", "VlmPrepConfig", "implementations.decision_cycle.perception.vlm_preparation.plugin", "VlmPrepConfig"),
    ("implementations.perception.preparation", "VlmPrepPlugin", "implementations.decision_cycle.perception.vlm_preparation.plugin", "VlmPrepPlugin"),
    ("implementations.perception.preparation", "prepare_vlm_artifacts", "implementations.decision_cycle.perception.vlm_preparation.plugin", "prepare_vlm_artifacts"),
    ("implementations.perception.simulation", "SimColorTargetsPlugin", "implementations.decision_cycle.perception.sim_color_targets.plugin", "SimColorTargetsPlugin"),
    ("implementations.perception.traversability", "FloorPlaneConfig", "implementations.decision_cycle.perception.floor_plane.model", "FloorPlaneConfig"),
    ("implementations.perception.traversability", "StillProcessingResult", "implementations.decision_cycle.perception.floor_plane.model", "StillProcessingResult"),
    ("implementations.perception.traversability", "estimate_floor_mask", "implementations.decision_cycle.perception.floor_plane.model", "estimate_floor_mask"),
    ("implementations.perception.traversability", "process_still", "implementations.decision_cycle.perception.floor_plane.model", "process_still"),
    ("implementations.perception.traversability", "source_obstacle_hits", "implementations.decision_cycle.perception.floor_plane.model", "source_obstacle_hits"),

    # implementations.runtime
    ("implementations.runtime.donkeycar", "AutonomyPilotPart", "implementations.runtime.donkeycar.donkey_part", "AutonomyPilotPart"),
    ("implementations.runtime.donkeycar", "CAMERA_LATEST_FRAME_PATH", "implementations.runtime.donkeycar.donkey_part", "CAMERA_LATEST_FRAME_PATH"),
    ("implementations.runtime.donkeycar", "CAMERA_LATEST_JSON_PATH", "implementations.runtime.donkeycar.donkey_part", "CAMERA_LATEST_JSON_PATH"),
    ("implementations.runtime.donkeycar", "CAMERA_PUBLICATION_SCHEMA", "implementations.runtime.donkeycar.donkey_part", "CAMERA_PUBLICATION_SCHEMA"),
    ("implementations.runtime.donkeycar", "DECISION_LATEST_PATH", "implementations.runtime.donkeycar.donkey_part", "DECISION_LATEST_PATH"),
    ("implementations.runtime.donkeycar", "DECISION_PUBLICATION_SCHEMA", "implementations.runtime.donkeycar.donkey_part", "DECISION_PUBLICATION_SCHEMA"),
    ("implementations.runtime.donkeycar", "DEFAULT_OBSERVATION_INTERVAL_S", "implementations.runtime.donkeycar.donkey_part", "DEFAULT_OBSERVATION_INTERVAL_S"),
    ("implementations.runtime.donkeycar", "LATEST_FRAME_PATH", "implementations.runtime.donkeycar.donkey_part", "LATEST_FRAME_PATH"),
    ("implementations.runtime.donkeycar", "LATEST_JSON_PATH", "implementations.runtime.donkeycar.donkey_part", "LATEST_JSON_PATH"),
    ("implementations.runtime.donkeycar", "LatestCameraFrame", "implementations.runtime.donkeycar.donkey_part", "LatestCameraFrame"),
    ("implementations.runtime.donkeycar", "LatestObservationSnapshot", "implementations.runtime.donkeycar.donkey_part", "LatestObservationSnapshot"),
    ("implementations.runtime.donkeycar", "OBSERVATION_PUBLICATION_SCHEMA", "implementations.runtime.donkeycar.donkey_part", "OBSERVATION_PUBLICATION_SCHEMA"),
    ("implementations.runtime.donkeycar", "ONBOARD_OBSERVATION_SNAPSHOT_SCHEMA", "implementations.runtime.donkeycar.donkey_part", "ONBOARD_OBSERVATION_SNAPSHOT_SCHEMA"),

    # implementations.vehicle
    ("implementations.vehicle", "ChaseSimCar", "implementations.vehicle.chase_sim.car", "ChaseSimCar"),
    ("implementations.vehicle", "DonkeyPiCar", "implementations.vehicle.picar.car", "DonkeyPiCar"),
    ("implementations.vehicle", "create_local_car", "implementations.vehicle.picar.car", "create_local_car"),
    ("implementations.vehicle", "describe_local_car", "implementations.vehicle.picar.car", "describe_local_car"),
    ("implementations.vehicle.chase_sim", "ChaseCaptureValidationError", "implementations.vehicle.chase_sim.frame_identity", "ChaseCaptureValidationError"),
    ("implementations.vehicle.chase_sim", "ChasePassiveCaptureError", "implementations.vehicle.chase_sim.car", "ChasePassiveCaptureError"),
    ("implementations.vehicle.chase_sim", "ChaseSimCar", "implementations.vehicle.chase_sim.car", "ChaseSimCar"),
    ("implementations.vehicle.chase_sim", "align_candidate_with_shadow", "implementations.vehicle.chase_sim.frame_identity", "align_candidate_with_shadow"),
    ("implementations.vehicle.chase_sim", "build_chase_shadow_reference", "implementations.vehicle.chase_sim.frame_identity", "build_chase_shadow_reference"),
    ("implementations.vehicle.chase_sim", "evaluate_chase_evaluator_reference", "implementations.vehicle.chase_sim.frame_identity", "evaluate_chase_evaluator_reference"),
    ("implementations.vehicle.chase_sim", "format_chase_frame_id", "implementations.vehicle.chase_sim.frame_identity", "format_chase_frame_id"),
    ("implementations.vehicle.chase_sim", "score_shadow_alignment_batch", "implementations.vehicle.chase_sim.frame_identity", "score_shadow_alignment_batch"),
    ("implementations.vehicle.chase_sim", "simulator_epoch_from_snapshot", "implementations.vehicle.chase_sim.frame_identity", "simulator_epoch_from_snapshot"),
    ("implementations.vehicle.chase_sim", "simulator_frame_index_from_snapshot", "implementations.vehicle.chase_sim.frame_identity", "simulator_frame_index_from_snapshot"),
    ("implementations.vehicle.chase_sim", "validate_chase_sensor_capture", "implementations.vehicle.chase_sim.frame_identity", "validate_chase_sensor_capture"),
    ("implementations.vehicle.picar", "DonkeyPiCar", "implementations.vehicle.picar.car", "DonkeyPiCar"),
    ("implementations.vehicle.picar", "create_local_car", "implementations.vehicle.picar.car", "create_local_car"),
    ("implementations.vehicle.picar", "describe_local_car", "implementations.vehicle.picar.car", "describe_local_car"),
)
