from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from qca import (
    AnalysisError,
    AnalyzerConfig,
    analyze_diff,
    analyze_sources,
    analyze_tree,
    render_markdown,
    report_to_dict,
)
from qca.backtest import render_backtest_markdown, run_manifest
from qca.render import render_html


class QuantitativeChangeAnalysisTests(unittest.TestCase):
    def test_snapshot_classifies_and_excludes_non_code_from_core_measurements(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text(
                """import json\n\n\ndef choose(items):\n    if items and items[0]:\n        for item in items:\n            print(item)\n    return None\n""",
                encoding="utf-8",
            )
            (root / "tests").mkdir()
            (root / "tests" / "test_app.py").write_text(
                "def test_choose():\n    assert True\n", encoding="utf-8"
            )
            (root / "docs.md").write_text("# Notes\n\nnot Python\n", encoding="utf-8")
            (root / "generated.py").write_text(
                "# generated by fixture\nvalue = 1\n", encoding="utf-8"
            )
            (root / "evidence").mkdir()
            (root / "evidence" / "record.py").write_text("print('capture')\n", encoding="utf-8")
            (root / "evidence" / "result.json").write_text("{}\n", encoding="utf-8")

            report = analyze_tree(root, config=AnalyzerConfig(excluded_globs=("evidence/**",)))
            payload = report_to_dict(report)
            inventory = {item["path"]: item for item in payload["source_inventory"]}

            self.assertEqual(payload["head"]["file_count"], 6)
            self.assertEqual(payload["head"]["included_file_count"], 2)
            self.assertEqual(inventory["app.py"]["source_class"], "production")
            self.assertTrue(inventory["app.py"]["included"])
            self.assertEqual(inventory["tests/test_app.py"]["source_class"], "tests")
            self.assertEqual(inventory["docs.md"]["source_class"], "docs/configuration")
            self.assertFalse(inventory["docs.md"]["included"])
            self.assertEqual(inventory["generated.py"]["source_class"], "generated/runtime")
            self.assertFalse(inventory["generated.py"]["included"])
            self.assertEqual(inventory["evidence/record.py"]["source_class"], "tooling/scripts")
            self.assertEqual(inventory["evidence/result.json"]["source_class"], "generated/runtime")
            self.assertEqual(payload["head"]["decision_burden"], 3)
            self.assertEqual(
                [item["qualified_name"] for item in payload["head"]["callables"]],
                ["choose", "test_choose"],
            )

    def test_include_roots_preserve_inventory_but_limit_core_metrics(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")
            (root / "other.py").write_text("def other():\n    return 2\n", encoding="utf-8")

            report = analyze_tree(root, config=AnalyzerConfig(include_roots=("app.py",)))
            payload = report_to_dict(report)
            inventory = {item["path"]: item for item in payload["source_inventory"]}

            self.assertEqual(set(inventory), {"app.py", "other.py"})
            self.assertTrue(inventory["app.py"]["included"])
            self.assertFalse(inventory["other.py"]["included"])
            self.assertEqual(payload["head"]["included_file_count"], 1)
            self.assertEqual(payload["head"]["logical_loc"], 2)
            self.assertEqual(len(payload["head"]["callables"]), 1)

    def test_analyze_file_and_directory_without_git(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("def run(value):\n    if value:\n        return value\n    return 0\n")
            (root / "src").mkdir()
            (root / "src" / "lib.py").write_text("def lib():\n    return 1\n")
            (root / "tests").mkdir()
            (root / "tests" / "test_lib.py").write_text("def test_lib():\n    assert True\n")

            file_report = report_to_dict(analyze_tree(root / "app.py"))
            self.assertEqual(list(item["path"] for item in file_report["source_inventory"]), ["app.py"])
            self.assertEqual(file_report["source_inventory"][0]["source_class"], "production")
            self.assertGreater(file_report["head"]["decision_burden"], 0)

            directory = report_to_dict(analyze_tree(root))
            inventory = {item["path"]: item["source_class"] for item in directory["source_inventory"]}
            self.assertEqual(inventory["app.py"], "production")
            self.assertEqual(inventory["tests/test_lib.py"], "tests")
            self.assertGreater(directory["head"]["included_file_count"], 1)

            combined = report_to_dict(analyze_tree([root / "src", root / "tests"]))
            combined_paths = {item["path"] for item in combined["source_inventory"]}
            self.assertEqual(combined_paths, {"src/lib.py", "tests/test_lib.py"})
            classes = {item["path"]: item["source_class"] for item in combined["source_inventory"]}
            self.assertEqual(classes["src/lib.py"], "production")
            self.assertEqual(classes["tests/test_lib.py"], "tests")

            with self.assertRaises(AnalysisError):
                analyze_tree(root / "missing.py")

    def test_python_language_filter_drops_non_python_files(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("def run():\n    return 1\n")
            (root / "tests").mkdir()
            (root / "tests" / "test_app.py").write_text("def test_run():\n    assert True\n")
            (root / "README.md").write_text("# notes\n")
            (root / "view.html").write_text("<p>view</p>\n")
            (root / "data.json").write_text("{}\n")

            payload = report_to_dict(
                analyze_tree(root, config=AnalyzerConfig(languages=("python",)))
            )
            paths = [item["path"] for item in payload["source_inventory"]]
            self.assertEqual(paths, ["app.py", "tests/test_app.py"])
            classes = {item["path"]: item["source_class"] for item in payload["source_inventory"]}
            self.assertEqual(classes["app.py"], "production")
            self.assertEqual(classes["tests/test_app.py"], "tests")
            self.assertTrue(all(item["language"] == "python" for item in payload["source_inventory"]))

            completed = subprocess.run(
                [sys.executable, "-m", "qca", "analyze", str(root), "--python", "--json", str(root / "out.json")],
                cwd=Path(__file__).resolve().parents[2],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            cli = json.loads((root / "out.json").read_text(encoding="utf-8"))
            self.assertEqual(
                [item["path"] for item in cli["source_inventory"]],
                ["app.py", "tests/test_app.py"],
            )
            self.assertEqual(cli["configuration"]["languages"], ["python"])

    def test_analyze_sources_measures_in_memory_text(self) -> None:
        payload = report_to_dict(
            analyze_sources(
                {
                    "app.py": "def run():\n    return 1\n",
                    "tests/test_app.py": "def test_run():\n    assert True\n",
                    "README.md": "notes\n",
                },
                analyzed_path="memory",
            )
        )
        inventory = {item["path"]: item for item in payload["source_inventory"]}
        self.assertEqual(payload["identity"]["analyzed_path"], "memory")
        self.assertIsNone(payload["identity"]["head_sha"])
        self.assertEqual(inventory["app.py"]["source_class"], "production")
        self.assertEqual(inventory["tests/test_app.py"]["source_class"], "tests")
        self.assertFalse(inventory["README.md"]["included"])
        self.assertEqual(payload["head"]["included_file_count"], 2)
        self.assertGreater(payload["head"]["logical_loc"], 0)

    def test_cli_analyzes_a_file(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            target = root / "app.py"
            target.write_text("def run():\n    return 1\n")
            completed = subprocess.run(
                [sys.executable, "-m", "qca", "analyze", str(target)],
                cwd=Path(__file__).resolve().parents[2],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("app.py", completed.stdout)
            self.assertIn("production", completed.stdout)

    def test_git_diff_reports_changed_shape_and_actionable_targets(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "app.py").write_text(
                "def choose(value):\n    return value\n", encoding="utf-8"
            )
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "app.py").write_text(
                """import external_lib\n\n\ndef choose(value, fallback=False):\n    if value:\n        if fallback:\n            return value\n        return external_lib.normalize(value)\n    return None\n""",
                encoding="utf-8",
            )
            self._git(root, "add", "app.py")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(analyze_diff(base, head, path=root))
            diff = payload["diff"]

            self.assertEqual(diff["changed_files"], ["app.py"])
            self.assertEqual(diff["file_changes"][0]["source_class"], "production")
            self.assertTrue(diff["file_changes"][0]["included"])
            self.assertGreater(diff["added_lines"], 0)
            self.assertGreater(diff["deleted_lines"], 0)
            self.assertEqual(diff["churn"], diff["added_lines"] + diff["deleted_lines"])
            self.assertEqual(diff["decision_burden_delta"], 2)
            self.assertEqual(diff["new_import_edges"], ["app.py->external_lib"])
            callable_target = next(
                target
                for target in diff["review_targets"]
                if target["kind"] == "callable"
            )
            self.assertEqual(callable_target["action"], "inspect_callable")
            self.assertIn("decision count increased by 2", callable_target["reasons"])
            self.assertTrue(
                any(
                    target["kind"] == "dependency"
                    and target["edge"] == "app.py->external_lib"
                    for target in diff["review_targets"]
                )
            )

    def test_report_json_is_reproducible_for_same_tree(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("VALUE = 3\n", encoding="utf-8")
            first = report_to_dict(analyze_tree(root))
            second = report_to_dict(analyze_tree(root))
            self.assertEqual(first, second)
            self.assertIsNone(first["identity"]["head_sha"])
            self.assertTrue(first["identity"]["working_tree_digest"])
            (root / "untracked.py").write_text("EXTRA = 1\n", encoding="utf-8")
            changed = report_to_dict(analyze_tree(root))
            self.assertNotEqual(
                first["identity"]["working_tree_digest"],
                changed["identity"]["working_tree_digest"],
            )
            (root / "notes.txt").write_text("one\n", encoding="utf-8")
            first_notes = report_to_dict(analyze_tree(root))
            (root / "notes.txt").write_text("two\n", encoding="utf-8")
            second_notes = report_to_dict(analyze_tree(root))
            self.assertNotEqual(
                first_notes["identity"]["working_tree_digest"],
                second_notes["identity"]["working_tree_digest"],
            )
            completed = subprocess.run(
                [sys.executable, "-m", "qca", "analyze", str(root)],
                cwd=Path(__file__).resolve().parents[2],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("working-tree digest:", completed.stdout)

    def test_scoped_diff_and_exclusions_align_with_git_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "pkg").mkdir()
            (root / "pkg" / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            (root / "pkg" / "evidence").mkdir()
            (root / "pkg" / "evidence" / "capture.md").write_text("old\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "pkg" / "app.py").write_text(
                "def run():\n    if True:\n        return 2\n    return 1\n", encoding="utf-8"
            )
            (root / "pkg" / "evidence" / "capture.md").write_text("new evidence\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(
                analyze_diff(
                    base,
                    head,
                    path=root / "pkg",
                    config=AnalyzerConfig(excluded_globs=("evidence/**",)),
                )
            )
            diff = payload["diff"]
            self.assertEqual(diff["changed_files"], ["app.py", "evidence/capture.md"])
            self.assertEqual(
                [item["path"] for item in diff["file_changes"]],
                ["app.py", "evidence/capture.md"],
            )
            self.assertFalse(diff["file_changes"][1]["included"])
            self.assertEqual(diff["included_changed_files"], ["app.py"])
            self.assertEqual(diff["included_added_lines"], 2)
            self.assertEqual(diff["included_deleted_lines"], 0)
            self.assertEqual(diff["decision_burden_delta"], 1)
            self.assertTrue(diff["changed_callables"])
            self.assertEqual(diff["changed_callables"][0]["path"], "app.py")

    def test_diff_measures_scattered_file_collections(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "src").mkdir()
            (root / "tests").mkdir()
            (root / "src" / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            (root / "tests" / "test_app.py").write_text("def test_run():\n    return 1\n", encoding="utf-8")
            (root / "other.py").write_text("OTHER = 1\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "src" / "app.py").write_text(
                "def run():\n    if True:\n        return 1\n    return 0\n",
                encoding="utf-8",
            )
            (root / "tests" / "test_app.py").write_text("def test_run():\n    assert True\n", encoding="utf-8")
            (root / "other.py").write_text("OTHER = 2\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(analyze_diff(base, head, path=[root / "src", root / "tests"]))
            changed = set(payload["diff"]["changed_files"])
            self.assertEqual(changed, {"src/app.py", "tests/test_app.py"})
            classes = {item["path"]: item["source_class"] for item in payload["diff"]["file_changes"]}
            self.assertEqual(classes["src/app.py"], "production")
            self.assertEqual(classes["tests/test_app.py"], "tests")
            self.assertGreater(payload["diff"]["decision_burden_delta"], 0)

            revision = report_to_dict(analyze_tree([root / "src", root / "tests"], ref=head))
            self.assertEqual(
                {item["path"] for item in revision["source_inventory"]},
                {"src/app.py", "tests/test_app.py"},
            )

            completed = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "qca",
                    "diff",
                    "--base",
                    base,
                    "--head",
                    head,
                    "--path",
                    str(root / "src"),
                    "--path",
                    str(root / "tests"),
                    "--python",
                ],
                cwd=Path(__file__).resolve().parents[2],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("src/app.py", completed.stdout)
            self.assertIn("tests/test_app.py", completed.stdout)
            self.assertNotIn("other.py", completed.stdout)

    def test_git_diff_treats_rename_as_delete_plus_add_and_keeps_deletion_ranges(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "old.py").write_text("def old():\n    return 1\n", encoding="utf-8")
            (root / "delete.py").write_text("def gone():\n    return 0\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            os.rename(root / "old.py", root / "new.py")
            os.unlink(root / "delete.py")
            self._git(root, "add", "-A")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(analyze_diff(base, head, path=root))
            diff = payload["diff"]
            self.assertEqual(diff["changed_files"], ["delete.py", "new.py", "old.py"])
            changes = {(item["path"], item["qualified_name"]): item for item in diff["changed_callables"]}
            self.assertIsNone(changes[("new.py", "old")]["before"])
            self.assertIsNone(changes[("old.py", "old")]["after"])
            self.assertIsNone(changes[("delete.py", "gone")]["after"])

    def test_backtest_manifest_preserves_scale_and_questions(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "app.py").write_text("def run():\n    if True:\n        return 1\n    return 0\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()
            manifest = root / "manifest.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": "qca/m008-backtest/v1",
                        "path": str(root),
                        "config": {"include_roots": ["."]},
                        "experiment": {"hypothesis": "shape is inspectable"},
                        "states": [
                            {
                                "id": "fixture",
                                "scale": "small",
                                "base": base,
                                "head": head,
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )

            payload = run_manifest(manifest)
            self.assertEqual(payload["schema"], "qca/m008-backtest-report/v1")
            self.assertEqual(payload["experiment"]["hypothesis"], "shape is inspectable")
            self.assertEqual(payload["states"][0]["scale"], "small")
            self.assertTrue(payload["states"][0]["operator_questions"])
            self.assertTrue(payload["states"][0]["diff"]["review_targets"])
            self.assertTrue(payload["execution"]["all_revisions_resolved"])
            self.assertIn("shape is inspectable", render_backtest_markdown(payload))

    def test_production_vs_tests_split_covers_code_and_excludes_docs(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            (root / "tests").mkdir()
            (root / "tests" / "test_app.py").write_text("def test_run():\n    assert True\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "app.py").write_text(
                "def run():\n    return 1\n\ndef extra():\n    return 2\n",
                encoding="utf-8",
            )
            (root / "view.html").write_text("<p>view</p>\n", encoding="utf-8")
            (root / "tests" / "test_app.py").write_text(
                "def test_run():\n    assert True\n\ndef test_extra():\n    assert True\n",
                encoding="utf-8",
            )
            (root / "tests" / "data.json").write_text("{}\n", encoding="utf-8")
            (root / "README.md").write_text("notes\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            snapshot = report_to_dict(analyze_tree(root))
            split = snapshot["head"]["production_test_split"]
            by_class = snapshot["head"]["by_class"]
            self.assertEqual(split["classes"], ["production", "tests"])
            self.assertEqual(split["raw_loc"]["production"], by_class["production"]["raw_loc"])
            self.assertEqual(split["raw_loc"]["tests"], by_class["tests"]["raw_loc"])
            self.assertEqual(
                split["raw_loc"]["total"],
                split["raw_loc"]["production"] + split["raw_loc"]["tests"],
            )
            self.assertGreater(split["raw_loc"]["production"], 0)
            self.assertGreater(split["raw_loc"]["tests"], 0)
            self.assertEqual(
                split["raw_loc"]["production_share_permille"] + split["raw_loc"]["tests_share_permille"],
                1000,
            )
            self.assertTrue(
                any(item["source_class"] == "docs/configuration" for item in snapshot["source_inventory"])
            )

            report = analyze_diff(base, head, path=root)
            payload = report_to_dict(report)
            diff_split = payload["diff"]["production_test_split"]
            python = diff_split["python"]
            all_lines = diff_split["all_lines"]
            self.assertGreater(python["production"]["net_lines"], 0)
            self.assertGreater(python["tests"]["net_lines"], 0)
            self.assertEqual(
                python["total"]["net_lines"],
                python["production"]["net_lines"] + python["tests"]["net_lines"],
            )
            self.assertGreater(all_lines["production"]["net_lines"], python["production"]["net_lines"])
            self.assertGreater(all_lines["tests"]["net_lines"], python["tests"]["net_lines"])
            self.assertGreater(payload["diff"]["changed_by_class"]["docs/configuration"]["files"], 0)
            self.assertIn("Production vs tests", render_markdown(report))
            self.assertIn("Production vs tests", render_html(payload))

    @staticmethod
    def _git(root: Path, *args: str) -> str:
        completed = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return completed.stdout


if __name__ == "__main__":
    unittest.main()
