from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from qca import AnalyzerConfig, analyze_diff, analyze_tree, report_to_dict
from qca.backtest import render_backtest_markdown, run_manifest


class QuantitativeChangeAnalysisTests(unittest.TestCase):
    def test_snapshot_classifies_and_excludes_non_code_from_core_measurements(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text(
                """import json\n\n\ndef choose(items):\n    if items and items[0]:\n        for item in items:\n            print(item)\n    return None\n""",
                encoding="utf-8",
            )
            (root / "tests").mkdir()
            (root / "tests" / "test_app.py").write_text(
                "def test_choose():\n    assert True\n", encoding="utf-8"
            )
            (root / "docs.md").write_text("# Notes\n\nnot Python\n", encoding="utf-8")
            (root / "generated.py").write_text(
                "# generated by fixture\nvalue = 1\n", encoding="utf-8"
            )
            (root / "evidence").mkdir()
            (root / "evidence" / "record.py").write_text("print('capture')\n", encoding="utf-8")
            (root / "evidence" / "result.json").write_text("{}\n", encoding="utf-8")

            report = analyze_tree(root, config=AnalyzerConfig(excluded_globs=("evidence/**",)))
            payload = report_to_dict(report)
            inventory = {item["path"]: item for item in payload["source_inventory"]}

            self.assertEqual(payload["head"]["file_count"], 6)
            self.assertEqual(payload["head"]["included_file_count"], 2)
            self.assertEqual(inventory["app.py"]["source_class"], "production")
            self.assertTrue(inventory["app.py"]["included"])
            self.assertEqual(inventory["tests/test_app.py"]["source_class"], "tests")
            self.assertEqual(inventory["docs.md"]["source_class"], "docs/configuration")
            self.assertFalse(inventory["docs.md"]["included"])
            self.assertEqual(inventory["generated.py"]["source_class"], "generated/runtime")
            self.assertFalse(inventory["generated.py"]["included"])
            self.assertEqual(inventory["evidence/record.py"]["source_class"], "tooling/scripts")
            self.assertEqual(inventory["evidence/result.json"]["source_class"], "generated/runtime")
            self.assertEqual(payload["head"]["decision_burden"], 3)
            self.assertEqual(
                [item["qualified_name"] for item in payload["head"]["callables"]],
                ["choose", "test_choose"],
            )

    def test_include_roots_preserve_inventory_but_limit_core_metrics(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")
            (root / "other.py").write_text("def other():\n    return 2\n", encoding="utf-8")

            report = analyze_tree(root, config=AnalyzerConfig(include_roots=("app.py",)))
            payload = report_to_dict(report)
            inventory = {item["path"]: item for item in payload["source_inventory"]}

            self.assertEqual(set(inventory), {"app.py", "other.py"})
            self.assertTrue(inventory["app.py"]["included"])
            self.assertFalse(inventory["other.py"]["included"])
            self.assertEqual(payload["head"]["included_file_count"], 1)
            self.assertEqual(payload["head"]["logical_loc"], 2)
            self.assertEqual(len(payload["head"]["callables"]), 1)

    def test_git_diff_reports_changed_shape_and_actionable_targets(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "app.py").write_text(
                "def choose(value):\n    return value\n", encoding="utf-8"
            )
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "app.py").write_text(
                """import external_lib\n\n\ndef choose(value, fallback=False):\n    if value:\n        if fallback:\n            return value\n        return external_lib.normalize(value)\n    return None\n""",
                encoding="utf-8",
            )
            self._git(root, "add", "app.py")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(analyze_diff(base, head, path=root))
            diff = payload["diff"]

            self.assertEqual(diff["changed_files"], ["app.py"])
            self.assertEqual(diff["file_changes"][0]["source_class"], "production")
            self.assertTrue(diff["file_changes"][0]["included"])
            self.assertGreater(diff["added_lines"], 0)
            self.assertGreater(diff["deleted_lines"], 0)
            self.assertEqual(diff["churn"], diff["added_lines"] + diff["deleted_lines"])
            self.assertEqual(diff["decision_burden_delta"], 2)
            self.assertEqual(diff["new_import_edges"], ["app.py->external_lib"])
            callable_target = next(
                target
                for target in diff["review_targets"]
                if target["kind"] == "callable"
            )
            self.assertEqual(callable_target["action"], "inspect_callable")
            self.assertIn("decision count increased by 2", callable_target["reasons"])
            self.assertTrue(
                any(
                    target["kind"] == "dependency"
                    and target["edge"] == "app.py->external_lib"
                    for target in diff["review_targets"]
                )
            )

    def test_report_json_is_reproducible_for_same_tree(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "app.py").write_text("VALUE = 3\n", encoding="utf-8")
            first = report_to_dict(analyze_tree(root))
            second = report_to_dict(analyze_tree(root))
            self.assertEqual(first, second)
            self.assertIsNone(first["identity"]["head_sha"])
            self.assertTrue(first["identity"]["working_tree_digest"])
            (root / "untracked.py").write_text("EXTRA = 1\n", encoding="utf-8")
            changed = report_to_dict(analyze_tree(root))
            self.assertNotEqual(
                first["identity"]["working_tree_digest"],
                changed["identity"]["working_tree_digest"],
            )
            (root / "invalid.bin").write_bytes(b"\xff")
            invalid_first = report_to_dict(analyze_tree(root))
            (root / "invalid.bin").write_bytes(b"\xfe")
            invalid_second = report_to_dict(analyze_tree(root))
            self.assertNotEqual(
                invalid_first["identity"]["working_tree_digest"],
                invalid_second["identity"]["working_tree_digest"],
            )
            completed = subprocess.run(
                [sys.executable, "-m", "qca", "analyze", str(root)],
                cwd=Path(__file__).resolve().parents[2],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("working-tree digest:", completed.stdout)

    def test_scoped_diff_and_exclusions_align_with_git_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "pkg").mkdir()
            (root / "pkg" / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            (root / "pkg" / "evidence").mkdir()
            (root / "pkg" / "evidence" / "capture.md").write_text("old\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "pkg" / "app.py").write_text(
                "def run():\n    if True:\n        return 2\n    return 1\n", encoding="utf-8"
            )
            (root / "pkg" / "evidence" / "capture.md").write_text("new evidence\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(
                analyze_diff(
                    base,
                    head,
                    path=root / "pkg",
                    config=AnalyzerConfig(excluded_globs=("evidence/**",)),
                )
            )
            diff = payload["diff"]
            self.assertEqual(diff["changed_files"], ["app.py", "evidence/capture.md"])
            self.assertEqual(
                [item["path"] for item in diff["file_changes"]],
                ["app.py", "evidence/capture.md"],
            )
            self.assertFalse(diff["file_changes"][1]["included"])
            self.assertEqual(diff["included_changed_files"], ["app.py"])
            self.assertEqual(diff["included_added_lines"], 2)
            self.assertEqual(diff["included_deleted_lines"], 0)
            self.assertEqual(diff["decision_burden_delta"], 1)
            self.assertTrue(diff["changed_callables"])
            self.assertEqual(diff["changed_callables"][0]["path"], "app.py")

    def test_git_diff_treats_rename_as_delete_plus_add_and_keeps_deletion_ranges(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "old.py").write_text("def old():\n    return 1\n", encoding="utf-8")
            (root / "delete.py").write_text("def gone():\n    return 0\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            os.rename(root / "old.py", root / "new.py")
            os.unlink(root / "delete.py")
            self._git(root, "add", "-A")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()

            payload = report_to_dict(analyze_diff(base, head, path=root))
            diff = payload["diff"]
            self.assertEqual(diff["changed_files"], ["delete.py", "new.py", "old.py"])
            changes = {(item["path"], item["qualified_name"]): item for item in diff["changed_callables"]}
            self.assertIsNone(changes[("new.py", "old")]["before"])
            self.assertIsNone(changes[("old.py", "old")]["after"])
            self.assertIsNone(changes[("delete.py", "gone")]["after"])

    def test_backtest_manifest_preserves_scale_and_questions(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            self._git(root, "init", "-q")
            self._git(root, "config", "user.email", "qca@example.test")
            self._git(root, "config", "user.name", "QCA Tests")
            (root / "app.py").write_text("def run():\n    return 1\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "base")
            base = self._git(root, "rev-parse", "HEAD").strip()
            (root / "app.py").write_text("def run():\n    if True:\n        return 1\n    return 0\n", encoding="utf-8")
            self._git(root, "add", ".")
            self._git(root, "commit", "-qm", "head")
            head = self._git(root, "rev-parse", "HEAD").strip()
            manifest = root / "manifest.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": "qca/m008-backtest/v1",
                        "path": str(root),
                        "config": {"include_roots": ["."]},
                        "experiment": {"hypothesis": "shape is inspectable"},
                        "states": [
                            {
                                "id": "fixture",
                                "scale": "small",
                                "base": base,
                                "head": head,
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )

            payload = run_manifest(manifest)
            self.assertEqual(payload["schema"], "qca/m008-backtest-report/v1")
            self.assertEqual(payload["experiment"]["hypothesis"], "shape is inspectable")
            self.assertEqual(payload["states"][0]["scale"], "small")
            self.assertTrue(payload["states"][0]["operator_questions"])
            self.assertTrue(payload["states"][0]["diff"]["review_targets"])
            self.assertTrue(payload["execution"]["all_revisions_resolved"])
            self.assertIn("shape is inspectable", render_backtest_markdown(payload))

    @staticmethod
    def _git(root: Path, *args: str) -> str:
        completed = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return completed.stdout


if __name__ == "__main__":
    unittest.main()
